Task0_Mirzazyanov
EgorkaKulikov/spbu-se2019-spring pull request #1
Opened 2019-03-08 10:15 UTC by Glebuska

2019-03-12 20:00 UTC, EgorkaKulikov requested changes

2019-03-12 20:00 UTC, EgorkaKulikov commented on task01.kt
> +
Здесь большие вопросы по стилю: отступы, countofedges, длинные строки, обсудим....

2019-03-12 20:00 UTC, EgorkaKulikov commented on task01.kt
> +        val j = Random.nextInt(n)
Мб сразу в диапазоне i+1...n генерировать

2019-03-12 20:00 UTC, EgorkaKulikov commented on task01.kt
> +
Точно ли все юзинги нужны?

2019-03-12 20:00 UTC, EgorkaKulikov commented on task01.kt
> +    println("Number of vertex from 0 to ${n - 1} for DijkstraAlgo")
Непонятные логи...

2019-03-12 20:00 UTC, EgorkaKulikov commented on task01.kt
> +    val k = readLine()!!.toInt()
Не, чтение чего-либо с консоли внутри реализации алгоритма Дейкстры - неправильно

2019-03-12 20:00 UTC, EgorkaKulikov commented on task01.kt
> +    val d = Array(n) { 1000 }
Опасный хардкод. А если потом максимальное значение изменится, а у вас в каждом алгоритме такая константа будет? Да ещё и дальше проверка d[v] < 1000

2019-03-12 20:00 UTC, EgorkaKulikov commented on task01.kt
> +        var v = -1
Назначение переменной сразу не просматривается. Ну и имя d стоит оставить олимпиадкам

2019-03-12 20:00 UTC, EgorkaKulikov commented on task01.kt
> +        if (temp <= 0 || temp >= 1000) throw ExceptionInInitializerError()
А почему именно такое? Здесь же вроде нет статической инициализации класса и проблем с инициализацией его свойств...

2019-03-12 20:00 UTC, EgorkaKulikov commented on task01.kt
> +        else temp
По классике if () then положительный сценарий else исключение
Здесь наоборот

2019-03-12 20:00 UTC, EgorkaKulikov commented on task01.kt
> +    if(dDj == dFb) println("Algorithms are equel")
equal, и сообщение опять не очень

2019-03-12 20:00 UTC, EgorkaKulikov commented on task01.kt
> +}
За Котлин очень-очень сильно хвалю. Остальное придёт с опытом.

2019-03-13 12:40 UTC, Glebuska commented
Исправил недочеты. Жду новой критики)

2019-03-16 21:50 UTC, EgorkaKulikov commented on task01.kt
> +
стало заметно лучше,

2019-03-16 21:50 UTC, EgorkaKulikov commented on task01.kt
> +        val j = Random.nextInt(n)
Кажется, ещё актуально

2019-03-16 21:53 UTC, EgorkaKulikov commented on task01.kt
> +    val d = Array(n) { 1000 }
Вот это тоже так и осталось, нужно исправить.

2019-03-17 19:23 UTC, Glebuska commented on task01.kt
> +    val d = Array(n) { 1000 }
Я же вроде исправил константу на Int.Max_Value или проблема в другом?

2019-03-17 19:40 UTC, Glebuska commented on task01.kt
> +        val j = Random.nextInt(n)
Отступы подчистить забыл, косяк. Но не могу понять, чем такой способ заполнения рандомными числами не подходит. Если рассматривать диапазон 1..n, то в любом случае цикл сохраниться, разве что на одну проверку меньше будет. Читаемость? Не думаю, что это как-то мешает. Или я чего-то важного не замечаю?

2019-03-17 19:40 UTC, Glebuska commented on task01.kt
> +        val j = Random.nextInt(n)
Отступы подчистить забыл, косяк. Но не могу понять, чем такой способ заполнения рандомными числами не подходит. Если рассматривать диапазон 1..n, то в любом случае цикл сохраниться, разве что на одну проверку меньше будет. Читаемость? Не думаю, что это как-то мешает. Или я чего-то важного не замечаю?

2019-03-17 20:30 UTC, EgorkaKulikov commented on task01.kt
> +        val j = Random.nextInt(n)
Ок, только резолвлю я

2019-03-17 20:31 UTC, EgorkaKulikov commented on task01.kt
> +    val d = Array(n) { 1000 }
Почему-то я не увидел этого дифа

2019-03-17 20:32 UTC, EgorkaKulikov approved these changes

2019-03-17 20:38 UTC, Glebuska commented on task01.kt
> +        val j = Random.nextInt(n)
Это был экспериментальный клик на кнопку resolve:)

2019-03-26 19:19 UTC, merged