Task01_Akhmetyanov
EgorkaKulikov/spbu-se2019-spring pull request #11
Opened 2019-03-17 15:12 UTC by azat-akhm

2019-03-18 20:22 UTC, EgorkaKulikov requested changes

2019-03-18 20:22 UTC, EgorkaKulikov commented on Task01/main.kt
> +
Мне кажется, не очень правильно при каждом запросе максимального веса ребра обходить всю матрицу смежности. Гораздо разумнее такие характеристики подсчитывать на этапе построения.

2019-03-18 20:22 UTC, EgorkaKulikov commented on Task01/main.kt
> +    var isVisited = Array(graphMatrix.size) { false }
Кажется, isVisited можно сделать val.  Стоит проверить на этот счёт и другие места в коде.

2019-03-18 20:22 UTC, EgorkaKulikov commented on Task01/main.kt
> +    val numberOfNodes = readLine()!!.toInt()
Обратите внимание на обсуждение по поводу !! оператора в пулреквесте Сергея.

2019-03-18 20:22 UTC, EgorkaKulikov commented on Task01/main.kt
> +    }
https://kotlinlang.org/docs/reference/coding-conventions.html#formatting-control-flow-statements

2019-03-18 20:22 UTC, EgorkaKulikov commented on Task01/main.kt
> +            ) {
Кажется, скобку из if лучше на строку с условием

2019-03-18 20:22 UTC, EgorkaKulikov commented on Task01/main.kt
> +    println("Number of nodes: ${graphMatrix.size}")
Если вы очень часто обращаетесь к какой-то проперти (graphMatrix.size, например), то лучше вынести её в локальную переменную. Геттер может оказаться неожиданно долгим.

2019-03-21 16:55 UTC, azat-akhm commented on Task01/main.kt
> +
Тогда лучше переписать все с использованием класса и сделать их проперти графа? Потому что если для этого использовать глобальные переменные, будут проблемы, если захочется создать более одного графа(потеряются старые значения min, max)

2019-03-21 17:04 UTC, azat-akhm commented on Task01/main.kt
> +            ) {
Мне тоже не очень нравится, но это предлагается на сайте котлина
 "Put the closing parentheses of the condition together with the opening curly brace on a separate line"

https://kotlinlang.org/docs/reference/coding-conventions.html#formatting-control-flow-statements

2019-03-24 07:04 UTC, EgorkaKulikov approved these changes

2019-03-26 19:28 UTC, merged