Task03&Task04_Mirzazyanov
EgorkaKulikov/spbu-se2019-spring pull request #112
Opened 2019-05-22 19:31 UTC by Glebuska

2019-05-22 19:48 UTC, Glebuska commented
Промахнулся и удалил не ту ветку :(
Открываю заново
Все замечания, будут исправлены в ближайшее время

2019-05-23 11:41 UTC, Glebuska commented
Исправил this, добавил новые тесты, подправил реализацию итератора. 
Насчет выноса итератора: мое решение невозможно без сильной замены архитектуры(создать абстрактную BaseNode, чтобы положить корень дерева и так уже итерироваться). Архитектура у нас командная и у некоторых людей, как я вижу, уже приняли, так что ничего менять я не стал

2019-05-24 18:55 UTC, NikitaMishin requested changes
В общем, архитектура, конечно , меееееееееееееееееееех.
Тесты ок, но на будущее оставил пару комментариев
Итератор, все -таки надо поправить проблему с тем, что должен возвращать итератор
Деревья - ок, мелкие  замечания + рут должен быть скрыт от пользователя.
Что-то еще было в комментах.
А так норм

2019-05-24 18:55 UTC, NikitaMishin commented on AVLTree/AVLNode.kt
> +package AVLTree
именование пэкэджей- с маленькой буквы
https://stackoverflow.com/questions/12534302/why-should-java-package-name-be-lowercase

2019-05-24 18:55 UTC, NikitaMishin commented on AVLTree/AVLNode.kt
> +        when {
в таких слуая можно сделать lift
fun ... = when {
}

2019-05-24 18:55 UTC, NikitaMishin commented on AVLTree/AVLNode.kt
> +            node?.height == null -> throw Exception("Error, null node has'nt leaf")
hasn't )

2019-05-24 18:55 UTC, NikitaMishin commented on AVLTree/AVLTree.kt
> +package AVLTree
было выше

2019-05-24 18:55 UTC, NikitaMishin commented on AVLTree/AVLTree.kt
> +    var root: AVLNode<K, V>? = null
а мы хотим предосталвять пользователю доступ к руту?? Он ведь можнт все поломать

2019-05-24 18:55 UTC, NikitaMishin commented on AVLTree/AVLTree.kt
> +        when (noNullCur.getBalance()) {
тут вполне можно строчку пустую сделать, чтобы сделать код читаеме , как бы разбить на куски, выполняющие определенную подзадаччу

2019-05-24 18:55 UTC, NikitaMishin commented on AVLTree/AVLTree.kt
> +            }
аналогично

2019-05-24 18:55 UTC, NikitaMishin commented on binaryTree/BSTNode.kt
> +package binaryTree
собственно, делал уже замечание кому-то
"безобразно, но единообразно" если пэкэджи уж пошли с большой буквы, то надо продолжать придерживаться одного стиля

2019-05-24 18:55 UTC, NikitaMishin commented on binaryTree/BSTNode.kt
> +    var key: K,
а почему здесь не val,хотя в авл val?

2019-05-24 18:55 UTC, NikitaMishin commented on binaryTree/BinaryTree.kt
> +    override fun iterator() : Iterator<BSTNode<K, V>> =
через ноды, которые возвращает итеартор, пользователь сможет сломать дерево.
Либо модификаторы изменить полей , либо возвращать просто пару

2019-05-24 18:55 UTC, NikitaMishin commented on redBlackTree/RedBlackTree.kt
> +        while (cur != null) {
к слову о смысловом отделении частей кода, здесь вот пренос строки как раз в тему, например

2019-05-24 18:55 UTC, NikitaMishin commented on test/AVLTreeTest.kt
> +        val nodeToInsert = List(10000){it}
10к ни о чем для стресс теста)))

2019-05-24 18:55 UTC, NikitaMishin commented on test/AVLTreeTest.kt
> +            Tree.insert(x, x)
что мы должны тестить в дереве поиска в стресс тестах в основном?? ПОИСК, не вставку

2019-05-24 18:55 UTC, NikitaMishin commented on test/AVLTreeTest.kt
> +        var cur: AVLNode<Int, Int> = Tree.root ?: throw Exception("Insert error")
в тестах можно не кидать экспешны , есть же спец декораторы, если не ошибаюсь

2019-05-24 19:34 UTC, Glebuska commented on AVLTree/AVLNode.kt
> +package AVLTree
Да, это вроде ясно, но AVL - аббревиатура, которую принято писать заглавными буквами. А treeAVL как-то вообще не звучит.

2019-05-24 19:53 UTC, Glebuska commented
Изменил итератор, скрыл корень

2019-05-24 20:53 UTC, NikitaMishin commented on AVLTree/AVLNode.kt
> +package AVLTree
AVLTree.some
some- это что будет? зарезолвится вообще, если хочу из пэкэджа AVLTree что-то взять, а не класс

2019-05-24 20:58 UTC, NikitaMishin approved these changes

2019-05-25 12:39 UTC, EgorkaKulikov commented on AVLTree/AVLTree.kt
> +    var root: AVLNode<K, V>? = null
да, это важный вопрос

2019-05-25 12:39 UTC, EgorkaKulikov commented on binaryTree/BinaryTree.kt
> +    override fun iterator() : Iterator<BSTNode<K, V>> =
Никита про это Олегу как раз рассказывал

2019-05-25 12:40 UTC, EgorkaKulikov commented on test/AVLTreeTest.kt
> +        val nodeToInsert = List(10000){it}
у некоторых и 1000 как стресс позиционировалась

2019-05-25 12:40 UTC, NikitaMishin commented on test/AVLTreeTest.kt
> +        val nodeToInsert = List(10000){it}
этто да(

2019-05-25 12:40 UTC, EgorkaKulikov commented on test/AVLTreeTest.kt
> +            Tree.insert(x, x)
здесь не согласен, мы вполне может стресс-тестить всю его функциональность

2019-05-25 12:42 UTC, EgorkaKulikov commented on test/AVLTreeTest.kt
> +        var cur: AVLNode<Int, Int> = Tree.root ?: throw Exception("Insert error")
А в Котлин мире не принято кидать экспешены в тестах?
В дотнете кидают и не парятся, я также предлагал делать, я внёс плохое знание в массы

2019-05-25 12:42 UTC, EgorkaKulikov commented on test/AVLTreeTest.kt
> +        var cur: AVLNode<Int, Int> = Tree.root ?: throw Exception("Insert error")
В любом случае здесь предлагаю как есть оставить, но вообще интересно

2019-05-25 12:42 UTC, NikitaMishin commented on test/AVLTreeTest.kt
> +            Tree.insert(x, x)
но вставку точно надо, а ее нема)

2019-05-25 12:43 UTC, EgorkaKulikov commented on AVLTree/AVLTree.kt
> +    var root: AVLNode<K, V>? = null
хорошо, что исправил

2019-05-25 12:43 UTC, EgorkaKulikov approved these changes

2019-05-25 12:45 UTC, NikitaMishin commented on test/AVLTreeTest.kt
> +        var cur: AVLNode<Int, Int> = Tree.root ?: throw Exception("Insert error")
assertFailsWith есть, например

2019-05-25 12:46 UTC, NikitaMishin commented on test/AVLTreeTest.kt
> +        var cur: AVLNode<Int, Int> = Tree.root ?: throw Exception("Insert error")
https://kotlinlang.org/api/latest/kotlin.test/kotlin.test/assert-fails-with.html

2019-05-25 17:52 UTC, EgorkaKulikov commented on test/AVLTreeTest.kt
> +        var cur: AVLNode<Int, Int> = Tree.root ?: throw Exception("Insert error")
А, ну про такую штуку я знаю, да. Спасибо.

2019-05-25 17:52 UTC, merged