Task03_Lunev
EgorkaKulikov/spbu-se2019-spring pull request #127
Opened 2019-05-26 19:56 UTC by artemlunev2000

2019-05-27 20:50 UTC, EgorkaKulikov requested changes
Ну в общем ничего глобально и принципиально нового, примерно то же самое, что и у остальных с теми же характерными особенностями.

2019-05-27 20:50 UTC, EgorkaKulikov commented on Task03/AVLTree.kt
> +        internal fun balanceFactor() = ((right as AVLNode?)?.height ?: 0) -
Исходя из логики, это свойство, а не метод

2019-05-27 20:50 UTC, EgorkaKulikov commented on Task03/AVLTree.kt
> +            if (this.left != null) {
this лишние, leftCorrectness - непонятное имя, tmp в данном контексте тоже не очень

2019-05-27 20:50 UTC, EgorkaKulikov commented on Task03/AVLTree.kt
> +                val tmp = (this.right as AVLNode).verifyAVL()
Очень много где если as не сработает, то программа рухнет. Надеяться, что оно всегда сработает, опасно

2019-05-27 20:50 UTC, EgorkaKulikov commented on Task03/AVLTree.kt
> +        val newNode = super.innerInsert(key, value) as AVLNode
Кажется, innerInsert - на то и внутренний метод, чтобы делать свою, специфичную логику. А он вызывает метод базового класса. Странно...

2019-05-27 20:50 UTC, EgorkaKulikov commented on Task03/AVLTree.kt
> +        return if (root == null) {
Не уверен, что это вообще дерево

2019-05-27 20:50 UTC, EgorkaKulikov commented on Task03/AVLTreeTest.kt
> +    private fun randomAVLTree(size: Int): AVLTree<Int, Int> {
По поводу тестов на рандомный данных смотрите пулреквест Дулетова

2019-05-27 20:50 UTC, EgorkaKulikov commented on Task03/AVLTreeTest.kt
> +        val tree = randomAVLTree(10000)
Это не стресс, уже не раз отмечалось

2019-05-27 20:50 UTC, EgorkaKulikov commented on Task03/AVLTreeTest.kt
> +            assert(tree.isAVLTree())
В принципе идея юнит-теста - проверка атомарной логики, а не корректности целых структур данных

2019-05-27 20:50 UTC, EgorkaKulikov commented on Task03/BalancedSearchTree.kt
> +                return
Поворот дерева просто ничего не делает? Я не помню такого случая у Кормена. Может быть, это исключительная ситуация?

2019-05-27 20:50 UTC, EgorkaKulikov commented on Task03/BinarySearchTree.kt
> +    var size = 0
Очень неудачно использовать такое имя ещё и вдалеке от контекста, где оно используется

2019-05-29 19:54 UTC, artemlunev2000 commented on Task03/AVLTree.kt
> +                val tmp = (this.right as AVLNode).verifyAVL()
согласен, но все же при написании деревьев некоторые null можно предсказать ( по типу если соблюдалась структура дерева и мы в некотором случае, значит должен существовать дед или дядя и т. п. ), а там где этого сделать нельзя стоят явные проверки. В данной реализации ошибок уже не должно быть, (с большой вероятностью тесты бы ее все таки отловили) поэтому проблема остается только в случае добавления новой логики программы, что конечно же плохо

2019-05-29 19:56 UTC, artemlunev2000 commented on Task03/AVLTree.kt
> +        val newNode = super.innerInsert(key, value) as AVLNode
да, но вставка в авл и кч деревья начинаются с вставки как в обычное бинарное. возможно innerInsert не совсем удачное название

2019-05-29 19:58 UTC, artemlunev2000 commented on Task03/AVLTree.kt
> +        return if (root == null) {
пустое дерево, свойства авл дерева не нарушены

2019-05-29 20:05 UTC, artemlunev2000 commented on Task03/BalancedSearchTree.kt
> +                return
Если рассматривать случай поворота в деревьях, то такой ситуации возникать не должно, но если рассматривать левый поворот отдельно, то не понятно, что ему делать если нет правого потомка. Скорее это нужно во время поиска ошибок в программе

2019-05-29 20:12 UTC, artemlunev2000 commented
Знаю что ничего сильно нового не придумано, но архитектура довольно сильно диктует условия что писать и как, поэтому и все решения команды похожи

2019-06-02 20:35 UTC, merged