Task01_Kanashin
EgorkaKulikov/spbu-se2019-spring pull request #13
Opened 2019-03-18 19:03 UTC by KanashinDmitry

Add solution for Task01

2019-03-19 20:52 UTC, EgorkaKulikov requested changes
В целом хорошо, просьба подправить нюансы

2019-03-19 20:52 UTC, EgorkaKulikov commented on Task01/main.kt
> +    {
Мелочь, но я бы написал функцию getRandom(nunberNodes) = (0 until numberNodes).random(), благо в Котлине это можно сделать одной строчкой.
И не копипастил 4 раза.

2019-03-19 20:52 UTC, EgorkaKulikov commented on Task01/main.kt
> +
Вообще говоря, здравый смысл подсказывает, что вычисление характерных рёбер лучше делать на этапе построения графа и его обновления, а не при каждом запросе статистики обходить всю матрицу смежности.

2019-03-19 20:52 UTC, EgorkaKulikov commented on Task01/main.kt
> +    for (j in 0 until numberNodes-1)
А здесь точно until numberNodes-1?

2019-03-20 13:04 UTC, KanashinDmitry commented
Исправил недочеты

2019-03-24 07:06 UTC, EgorkaKulikov approved these changes

2019-03-26 19:29 UTC, merged