Task01 solution (graphs) was added
EgorkaKulikov/spbu-se2019-spring pull request #14
Opened 2019-03-19 20:50 UTC by DanielELog

2019-03-19 21:01 UTC, EgorkaKulikov requested changes

2019-03-19 21:01 UTC, EgorkaKulikov commented on Task01/graphs.kt
> +
Ой, а зачем свой min/max? Я точно у других видел импорты какие-то хорошие для этого.

2019-03-19 21:01 UTC, EgorkaKulikov commented on Task01/graphs.kt
> +    for (i in 1..min(numVertex * (numVertex - 1) / 2, numEdge)) { // just to make sure I wrote correct [numEdge]
комментарий нужно строчкой выше поставить, а то она нечитаемо длинная

2019-03-19 21:01 UTC, EgorkaKulikov commented on Task01/graphs.kt
> +            secondV = (firstV + 1..numVertex - 1).random()
С until не будет немного приятнее читаться? Как ниже сделано?

2019-03-19 21:01 UTC, EgorkaKulikov commented on Task01/graphs.kt
> +
Мне кажется, при каждом запросе статистики обходить всю матрицу смежности означает повесить систему.

2019-03-19 21:01 UTC, EgorkaKulikov commented on Task01/graphs.kt
> +    /* [start] should be in range [0, graph.size)
Вот это круто, кстати. А стиль оформления официальный котлиновский?

2019-03-19 21:01 UTC, EgorkaKulikov commented on Task01/graphs.kt
> +    // see [dijkstra] comment
А вот так лучше не делать. Человек, который обновит документацию там, ни секунды не подумает о том, что потенциально отламывает её здесь. И никакой решарпер и тому подобные тулы ему не помогут.

2019-03-19 21:01 UTC, EgorkaKulikov commented on Task01/graphs.kt
> +
Я бы ещё такие маленький функции оформлял в стиле 
fun min = if (a<b) a else b

2019-03-19 21:02 UTC, EgorkaKulikov commented
И нужно переименовать в Task01_Logunov

2019-03-20 16:14 UTC, DanielELog commented on Task01/graphs.kt
> +    // see [dijkstra] comment
Постарался учесть все замечания. Можете перепроверить.

2019-03-24 07:08 UTC, EgorkaKulikov approved these changes

2019-03-26 19:29 UTC, merged