Task01_Shaposhnikov
EgorkaKulikov/spbu-se2019-spring pull request #16
Opened 2019-03-20 09:29 UTC by Shaposhnikov-Alexey

2019-03-24 07:18 UTC, EgorkaKulikov requested changes

2019-03-24 07:18 UTC, EgorkaKulikov commented on Shaposhnikov/Task01/main.kt
> +
Очень много закомментированного кода, который вряд ил будет нужен в дальнейшем

2019-03-24 07:18 UTC, EgorkaKulikov commented on Shaposhnikov/Task01/main.kt
> +const val maxDistance = 1000
Странно, если макс вес ребра 100, то пути длиной больше 10 рёбер уже могут превысить maxDistance?

2019-03-24 07:18 UTC, EgorkaKulikov commented on Shaposhnikov/Task01/main.kt
> +    val nodes = readLine()!!.toInt()
Лучше в случае неудачи readline самим кидать разумное исключение

2019-03-24 07:18 UTC, EgorkaKulikov commented on Shaposhnikov/Task01/main.kt
> +fun statistics(array : Array<Array<Int>>) {
Кажется, ТЗ на функцию статистики было немного иным

2019-03-24 07:18 UTC, EgorkaKulikov commented on Shaposhnikov/Task01/main.kt
> +    var min = 100
Опять непредсказуемый хардкод

2019-03-26 17:10 UTC, Shaposhnikov-Alexey commented on Shaposhnikov/Task01/main.kt
> +    var min = 100
Fixed listed issues

2019-03-26 19:30 UTC, EgorkaKulikov approved these changes

2019-03-26 19:30 UTC, merged