Task01_Privalihin
EgorkaKulikov/spbu-se2019-spring pull request #2
Opened 2019-03-08 10:37 UTC by AlekseiPrivalihin

2019-03-16 20:39 UTC, EgorkaKulikov requested changes

2019-03-16 20:39 UTC, EgorkaKulikov commented on Privalihin/Task01/src/Main.kt
> +        maxWeight = 0
А если эти переменные всё равно var, то можно было их выставить вне init блока же, просто написав 
private var minWeight : Int = 0? 
Или я что-то путаю?

2019-03-16 20:39 UTC, EgorkaKulikov commented on Privalihin/Task01/src/Main.kt
> +        adjMat = Array(N){ _ -> Array(N) { _ -> 0 } }
Можно без _, просто {0}

2019-03-16 20:39 UTC, EgorkaKulikov commented on Privalihin/Task01/src/Main.kt
> +        var freeEdges = Array<Array<Pair<Int, Int>>>(adjMat.size) { i -> Array(adjMat.size - i - 1) { j -> Pair(i, i + j + 1) } }
Строка кода настолько длинная, что не влезла даже в окошко гитхаба. Читателю с маленьким монитором будет грустно. Это кажется мелочью, но когда 95% кода пишется из офиса на огромных мониках, а потом в приболевшем состоянии работаешь из дома с меньшего экрана ноута, то ощущаешь всю боль....

2019-03-16 20:39 UTC, EgorkaKulikov commented on Privalihin/Task01/src/Main.kt
> +            if (maxWeight < weight)
https://stackoverflow.com/questions/2125066/is-it-a-bad-practice-to-use-an-if-statement-without-curly-braces
а также ещё могут быть проблемы мержда в гите, если без скобочек вложенность будет....

2019-03-16 20:39 UTC, EgorkaKulikov commented on Privalihin/Task01/src/Main.kt
> +            adjMat[freeEdges[i].first][freeEdges[i].second] = weight
В промышленном коде лучше выносить в переменные и проверять, что индекс попадает в диапазон. Любые выборки array[хрен знает что] опасны. Но для данной учебной задачи норм.

2019-03-16 20:39 UTC, EgorkaKulikov commented on Privalihin/Task01/src/Main.kt
> +        val edges = Array<Array<Pair<Int, Int>>>(adjMat.size) { i -> Array(adjMat.size) { j -> Pair(i, j) } }
Похоже на копипаст. Может вынесем чудесную генерацию рёбер в отдельный метод? Или сделаем его частью CreateRandomGraph.

2019-03-16 20:39 UTC, EgorkaKulikov commented on Privalihin/Task01/src/Main.kt
> +        for (i in 0..(M - 1)) {
until

2019-03-17 11:01 UTC, AlekseiPrivalihin commented on Privalihin/Task01/src/Main.kt
> +        maxWeight = 0
я наивно полагал, что вне init-блока нельзя пользоваться параметрами конструктора, а тогда генерация adjMat лезла бы в init-блок, и тогда бы было логично сгруппировать всю инициализацию в init-блоке. Но оказалось, что таки можно

2019-03-17 11:01 UTC, AlekseiPrivalihin commented on Privalihin/Task01/src/Main.kt
> +        adjMat = Array(N){ _ -> Array(N) { _ -> 0 } }
поменял

2019-03-17 11:02 UTC, AlekseiPrivalihin commented on Privalihin/Task01/src/Main.kt
> +        var freeEdges = Array<Array<Pair<Int, Int>>>(adjMat.size) { i -> Array(adjMat.size - i - 1) { j -> Pair(i, i + j + 1) } }
перенес первые фигурные скобочки, но честно говоря, выглядит немного странно теперь. Можно было бы, конечно, удалить аннотацию типа, но в данном случае мне кажется, что делать этого не стоит

2019-03-17 11:02 UTC, AlekseiPrivalihin commented on Privalihin/Task01/src/Main.kt
> +            if (maxWeight < weight)
добавил скобки во всех условных операторах

2019-03-17 11:04 UTC, AlekseiPrivalihin commented on Privalihin/Task01/src/Main.kt
> +            adjMat[freeEdges[i].first][freeEdges[i].second] = weight
Вообще это правда, но в данном случае ничего не может вылезти за границы исходя из принципа генерации freeEdges. При прочтении это действительно может быть неочевидно. Может быть, стоит добавить комментарий?

2019-03-17 11:07 UTC, AlekseiPrivalihin commented on Privalihin/Task01/src/Main.kt
> +        val edges = Array<Array<Pair<Int, Int>>>(adjMat.size) { i -> Array(adjMat.size) { j -> Pair(i, j) } }
edges здесь генерируется все же не совсем так, как freeEdges в addRandomEdges. Можно было бы вынести в отдельный метод генерацию массива distances, благо она одинаковая и в Дейкстре, и в Форде-Беллмане, но это был бы не очень содержательный метод, да еще и с контринтуитивным названием - назвать его getDistances, при том, что он возвращает не сами расстояния, а просто заготовку для алгоритмов поиска кратчайшего пути было бы странно. InitializeDistances? Тоже странно и не передает сути. Оставил как было

2019-03-17 11:08 UTC, AlekseiPrivalihin commented on Privalihin/Task01/src/Main.kt
> +        for (i in 0..(M - 1)) {
поменял везде 0..(<something> - 1) на 0.until(<something>).

2019-03-17 20:34 UTC, EgorkaKulikov commented on Privalihin/Task01/src/Main.kt
> +            adjMat[freeEdges[i].first][freeEdges[i].second] = weight
Я думаю здесь сойдёт  и так. Вряд ли комментарий в данном случае чему-то особенно поможет.

2019-03-17 20:34 UTC, EgorkaKulikov commented on Privalihin/Task01/src/Main.kt
> +        val edges = Array<Array<Pair<Int, Int>>>(adjMat.size) { i -> Array(adjMat.size) { j -> Pair(i, j) } }
Хорошо

2019-03-17 20:36 UTC, EgorkaKulikov approved these changes

2019-03-26 19:19 UTC, merged