Task02_Mirzazyanov
EgorkaKulikov/spbu-se2019-spring pull request #26
Opened 2019-04-09 19:15 UTC by Glebuska

2019-04-19 10:16 UTC, NikitaMishin commented on CodeReview.txt
> +"notOptimalConverte" соответственно - нет.
не понял вашу фразу: "cоотственно - нет". Соотвественно,  не конвертирует что ли?

2019-04-19 10:22 UTC, NikitaMishin commented on CodeReview.txt
> +fun Interpreter, которая интерпретирует символы, полученные на языке brainfuck
такую функцию не нашел, имелась в виду interpret ?

2019-04-19 10:23 UTC, NikitaMishin commented on CodeReview.txt
> +public fun compile, которая возвращает массив байт(байт-код для Java)
что вообще принимает функция на вход?

2019-04-19 10:23 UTC, NikitaMishin commented on CodeReview.txt
> +object Token, где перечисляются набор команд
какие конкретно команды?

2019-04-19 10:24 UTC, NikitaMishin requested changes
в целом, ок. Мне бы хотелось немного больше подробностей насчет некоторых функций. Ну и можно чуть про тесты написать (необязательно)

2019-04-19 10:27 UTC, NikitaMishin commented on CodeReview.txt
> +public fun compile, которая возвращает массив байт(байт-код для Java)
и нет ли каких-либо побочных действий в функции? например, зачем она принимает на вход название файла?

2019-04-19 12:34 UTC, Glebuska commented on CodeReview.txt
> +"notOptimalConverte" соответственно - нет.
Не используя цикл. Когда писал, думал что и так понятно, перечитав спустя несколько дней, понял, что не так уж и понятно)

2019-04-19 12:36 UTC, Glebuska commented on CodeReview.txt
> +fun Interpreter, которая интерпретирует символы, полученные на языке brainfuck
Да, опечатка

2019-04-19 12:41 UTC, Glebuska commented on CodeReview.txt
> +object Token, где перечисляются набор команд
На мой взгляд, команды тривиальные, чтобы их перечислять. Не хотел, чтобы показалось, что просто лью воду, для раздутия объема написанного

2019-04-19 14:23 UTC, NikitaMishin commented on CodeReview.txt
> +object Token, где перечисляются набор команд
согласен, а вот  по поводу функции compile хотелось бы чуть больше описания, там что-то интересное происходить должно

2019-04-21 11:12 UTC, EgorkaKulikov commented on CodeReview.txt
> +public fun compile, которая возвращает массив байт(байт-код для Java)
это вроде ещё актуальный вопрос, в остальном готов выкладывать

2019-04-21 16:36 UTC, NikitaMishin approved these changes
есть пара опечаток (дейсвия выполняем)  и запятая , но замечания учтены, спасибо

2019-04-28 19:04 UTC, merged