Task03&Task04_Kuzivanov
EgorkaKulikov/spbu-se2019-spring pull request #28
Opened 2019-04-10 16:25 UTC by SergeyKuz1001

2019-04-28 19:50 UTC, EgorkaKulikov requested changes

2019-04-28 19:50 UTC, EgorkaKulikov commented on Task03/AVLNode.kt
> +                if (right!!.deltaHeight == 1)
Если это публичная функция, то на вход ей может подъехать какая угодно гадость. Поэтому код, изобилующий предположениями о том, что right != null && left != null, откровенно смущает.

2019-04-28 19:50 UTC, EgorkaKulikov commented on Task03/AVLNode.kt
> +    override fun createNode(key: K, value: V): AVLNode<K, V> = AVLNode(key, value)
Вот это кстати очень правильное решение. Потому что потом создание может измениться и стать уже не на одну строчку, а в 25 местах изменять не придётся.

2019-04-28 19:50 UTC, EgorkaKulikov commented on Task03/AVLNode.kt
> +            2 -> {
Я бы здесь добавил комментарий, что такое -2 и 2 и почему ими всё исчерпывается. Я понял только потому, что умею строить АВЛ-дерево.

2019-04-28 19:50 UTC, EgorkaKulikov commented on Task03/AVLNode.kt
> +    override fun toString(): String = "($key to $value, height: $height)"
Реализация выглядит очень странно. Это не принципиально, просто не понял логики.

2019-04-28 19:50 UTC, EgorkaKulikov commented on Task03/AVLTree.kt
> +        this.root = root
Выглядит немного странно: создавать дерево, передавая в конструктор одну из его вершин. С точки зрения логики странно. Была ли в этом реальная необходимость?

2019-04-28 19:50 UTC, EgorkaKulikov commented on Task03/AVLTree.kt
> +        val node = path.last()
А не рухнет тут на пустом списке?

2019-04-28 19:50 UTC, EgorkaKulikov commented on Task03/AVLTree.kt
> +fun <K: Comparable<K>, V>avlTreeOf(vararg elements: Pair<K, V>): AVLTree<K, V> =
Вот это тоже здорово.

2019-04-28 19:50 UTC, EgorkaKulikov commented on Task03/BalancingNode.kt
> +abstract class BalancingNode<K: Comparable<K>, V, NT: BalancingNode<K, V, NT>>: Node<K, V, NT>() {
Надо было, конечно, ещё раз пообсуждать ваши схемы архитектуры и подумать над именованиями. BalancingNode звучит не очень, rotateLeftBig особенно не очень, но тут уже ничего не поделаешь, видимо, просто у сведению.

2019-04-28 19:50 UTC, EgorkaKulikov commented on Task03/Node.kt
> +    LeftSon, RightSon, Root
Лучше в столбик и с плавающей запятой после последнего, иначе при добавлении могут возникать ненужные конфликты мёрджа.

2019-04-28 19:50 UTC, EgorkaKulikov commented on Task03/Node.kt
> +    val type: TypeSon
Вот здесь тоже мне понралось, как с геттерами и сеттерами сделано.

2019-04-28 19:50 UTC, EgorkaKulikov commented on Task03/TestsForBSTree.kt
> +    @DisplayName("Test #1: Simple test for structure tree")
Непонятно, что проверяет этот тест. И из имени test1 Это тоже непонятно.

2019-04-28 19:50 UTC, EgorkaKulikov commented on Task03/TestsForBSTree.kt
> +        assert(tree.isCorrect())
Ненене, слишком много ассёртов. . По классике один тест - проверка одной единицы логики. Иногда от этого немного отступают, но не настолько.

2019-04-28 19:50 UTC, EgorkaKulikov commented on Task03/TestsForBSTree.kt
> +        assert(tree.isCorrect())
Похоже, это проблема всех тестов.

2019-04-29 07:43 UTC, SergeyKuz1001 commented on Task03/AVLNode.kt
> +                if (right!!.deltaHeight == 1)
то, что right != null выполнится 100%, так как deltaHeight = высота левого поддерева - высота правого, высота левого >= 0 всегда, и когда deltaHeight == -2, то высота правого поддерева >= 2. аналогично с left

2019-04-29 07:45 UTC, SergeyKuz1001 commented on Task03/AVLNode.kt
> +    override fun toString(): String = "($key to $value, height: $height)"
это просто планировалось для тестирования, в новых тестах будет уже не актуально

2019-04-29 07:48 UTC, SergeyKuz1001 commented on Task03/AVLTree.kt
> +        this.root = root
нет, не было, просто мне показалось, что уметь строить дерево как поддерево от любой вершины может быть иногда полезно

2019-04-29 07:54 UTC, SergeyKuz1001 commented on Task03/AVLTree.kt
> +        val node = path.last()
в path у меня хранятся вершины от корня до нужного листа, и path может быть пуст только тогда, когда root == null, но этот вариант у меня обрабатывается в setWithInfo, откуда данная функция и вызывается. поэтому если сделать функцию приватной, то path точно не будет пуст

2019-04-29 13:04 UTC, SergeyKuz1001 commented
недочёты исправил, тесты пока убрал (но они будут), пересмотрел приватность и публичность некоторых методов

2019-05-06 18:51 UTC, EgorkaKulikov commented on Task03/AVLNode.kt
> +    NodeWithBalancing<K, V, AVLNode<K, V>>() {
Всё-таки название NodeWithBalancing уж больно не очень. Второй раз открываю и вводит в заблуждение.

2019-05-06 18:53 UTC, EgorkaKulikov commented on Task03/AVLNode.kt
> +        private set(value) { field = value }
А в Котлине нельзя, подобно дотнету, написать просто private set, если подразумевается вот такая реализация?

2019-05-06 18:53 UTC, EgorkaKulikov commented on Task03/AVLNode.kt
> +    protected override fun rotateLeft() {
Давайте отделим функции друг от друга пустой строкой, так совсем тяжело читать.

2019-05-06 18:54 UTC, EgorkaKulikov commented on Task03/AVLNode.kt
> +    public override fun copy() = AVLNode(key, value)
кстати, а если value - очень сложная ссылочная структура, нормально ли она скопируется? Не будет ли тут поверхностного копирования?

2019-05-06 18:56 UTC, EgorkaKulikov commented on Task03/Node.kt
> +enum class TypeSon {
SonType

2019-05-06 18:58 UTC, EgorkaKulikov commented on Task03/Node.kt
> +    fun moveOnNewPlace(newPlace: NT) {
Плохое название

2019-05-06 18:59 UTC, EgorkaKulikov commented on Task03/Node.kt
> +    fun findKey(key: K): TypeSon =
findKeyType ? findKey это просто find по идее

2019-05-06 19:00 UTC, EgorkaKulikov commented on Task03/NodeWithBalancing.kt
> +        val father = parent!!
Очень неинтуитивно, что здесь не упадёт при попытке повернуть за корень.

2019-05-06 19:03 UTC, EgorkaKulikov requested changes
Нужен результат прогона тестов, помимо остальных замечаний

2019-05-06 19:03 UTC, EgorkaKulikov commented on Task03/Tree.kt
> +    NodeCreate, NodeUpdate, NodeDelete, NodeNotFounded
Лучше в столбик и с плавающей запятой
Кажется, на самом деле это Status: created, updated итд

2019-05-07 17:03 UTC, SergeyKuz1001 commented on Task03/Node.kt
> +enum class TypeSon {
этот тип подразумевается как тип вершины как сына своего родителя, то есть для родителя он левый или правый сын (а если родителя нет, то он корень)

2019-05-07 17:11 UTC, SergeyKuz1001 commented on Task03/AVLNode.kt
> +    public override fun copy() = AVLNode(key, value)
да, будет, но функция copy() используется только при удалении из красно-чёрного дерева для того, чтобы для вершины, которую надо удалить, находить вершину со следующим ключом, создавать копию и вставлять на место старой вершины (которую как раз и хотим удалить), и в итоге "оригинальная" вершина, для которой вызывался метод copy(), пропадёт по алгоритму удаления, поэтому в данном случае это не сильно важно, что у value будет поверхностное копирование

2019-05-07 17:13 UTC, SergeyKuz1001 commented
недочёты постарался исправить, добавил командные тесты, жду новых комментариев)

2019-05-07 19:22 UTC, EgorkaKulikov commented
Код вроде удалось в некоторой степени улучшить, тут аппрув. По тестам завтра обсудим.

2019-05-07 21:37 UTC, EgorkaKulikov commented on Task03/AVLNode.kt
> +    override fun createNode(key: K, value: V): AVLNode<K, V> = AVLNode(key, value)
@KutuevVladimir правильно заметил, что идея правильна только наполовину. Вообще говоря, для порождения объектов обычно используют так называемые фабрики, довольно распространённый паттерн. Это больше для общего развития, а не призыв к исправлению.

2019-05-07 22:00 UTC, KutuevVladimir commented on Task03/AVLNode.kt
> +    override fun createNode(key: K, value: V): AVLNode<K, V> = AVLNode(key, value)
Тут немного странно, что узлы пораждают новые узлы, что требует такой заморочки. Гораздо логичнее, чтобы дерево отвечало за создание узлов, отслеживание инвариантов, связанных с узлами.
Тут как раз просматривается паттерн фабричный метод: у абстрактного дерева (`Tree`) есть метод которому нужно создать новый узел (`doSomething`) и абстрактный метод создания узла(`createNode(params):Node`). Тогда, например, красно-чёрное дерево (`RBTree`) переопределит создание узла: вызов конструктора у красно-чёрного узла: (`override fun createNode(params):Node {RBNode(params)}`)

2019-05-16 22:33 UTC, EgorkaKulikov commented
@SergeyKuz1001 Здесь попрошу добавить хотя бы несколько тестов на исключительные ситуации, обновить и приложить результат тестового прогона. После этого зачту задачи 3-4 полностью.

2019-05-21 17:38 UTC, merged