Task02_Akhmetyanov
EgorkaKulikov/spbu-se2019-spring pull request #29
Opened 2019-04-14 13:33 UTC by azat-akhm

2019-04-20 21:10 UTC, Tiltedprogrammer requested changes

2019-04-20 21:10 UTC, Tiltedprogrammer commented on Task02/review
> +на BF, выводящую заданную строку.
Это, безусловно, так и есть, но в классе как минимум больше методов (но все еще не так много, чтобы не написать про каждый), т.е. возможно стоило бы написать чуть-чуть поподробней, как если бы вы писали Javadoc к этим классам и методам. Это лишь с той целью, чтобы выделить возможные недочеты в коде.

> функция toBF конвертирует ее в вывод на brainfuck по одному символу

функция все же конвертирует не строку, а 1 символ

2019-04-20 21:10 UTC, Tiltedprogrammer commented on Task02/review
> +вызывает функции, соответствующие командам языка(inc, dec, openLoop и т.д.)
Те же самые замечания, например, можно написать, что вся семантика языка заключается в возврате выходной строки. (та что out в интерпретаторе)

2019-04-20 21:10 UTC, Tiltedprogrammer commented on Task02/review
> +генерации байт-кода.
Это тоже верно, но там есть еще много методов, которые что-то делают. Например, такой `loadClassAndRun`

Подводя итог, хочется связный отчет (как связаны компоненты и логика работы более низкоуровневая, нежели интерпретатор интерпретирует, компилятор компилирует), а это пока больше похоже на набросок из сигнатур у методов.

2019-04-20 21:10 UTC, Tiltedprogrammer commented on Task02/review
> +В ревью вполне справедливое замечание о том, что лучше явно указывать модификаторы доступа
Тут ревьюер тех лет немного схалтурил. Модификаторы и правда нужно указывать, но не public.

2019-04-20 21:10 UTC, Tiltedprogrammer commented on Task02/review
> +использовать until, который введен уже с версии 1.0
Согласен, добавлю еще что в целом код написан так себе в смысле выдержки какого-то style guid'a, местами есть пробелы там, где не должны, хромает именование (те же классы пишутся без андерскоров и в кемел кейсе) var'ы вместо var'ов и т.д. В общем, если вы откроете этот пул реквест в IDEA, то она вам на все укажет.

2019-04-20 21:10 UTC, Tiltedprogrammer commented on Task02/review
> +использовать until, который введен уже с версии 1.0
так же `var out = ""` не очень хорошо, обычно пользуются stringBuilder

2019-04-20 21:42 UTC, Tiltedprogrammer commented on Task02/review
> +использовать until, который введен уже с версии 1.0
вот к слову сам стайл [гайд](https://kotlinlang.org/docs/reference/coding-conventions.html)

2019-04-20 22:16 UTC, Tiltedprogrammer commented on Task02/review
> +генерации байт-кода.
Плюс было бы интересно если бы расписали, как происходит компиляция отдельной инструкции языка BF  в JVM, например, такой ```'.' -> {
                    mv.visitFieldInsn(GETSTATIC, "java/lang/System", "out", "Ljava/io/PrintStream;")
                    .....
                    mv.visitMethodInsn(INVOKEVIRTUAL, "java/io/PrintStream", "print", "(C)V", false)
}```

2019-04-28 19:11 UTC, EgorkaKulikov commented
Вопрос  автору: какой тут статус? Нужно исправлять замечания?

2019-04-29 15:33 UTC, Tiltedprogrammer approved these changes
В принципе стало лучше, поэтому аппрув. Однако, рекомендую посмотреть комментарии, т.к. на мой взгляд этого в ревью не хватает, ну и ответить на некоторые из них, так для развития.

2019-04-29 15:33 UTC, Tiltedprogrammer commented on Task02/review
> +  программы. При некорректном вводе out содержит предупреждение "Input error"
Еще она сообщает о заходе за границы массива и ничего не говорит о том, если `[ ]` в программе некорректны

2019-04-29 15:33 UTC, Tiltedprogrammer commented on Task02/review
> +  инструкции языка, возвращает сгенерированное представление класса в объекте ClassWriter
Когда метод заполняет "заголовок" java-класса внутри `ClassWriter`, то название класса всегда `"Compiler_brainfuck"`, хотя генерируется все таки не компилятор, а программа с bf. 
Потом метод определяет функцию `main` и уже `MethodVisitor` вставляет в `main` байткод-инструкции, соответствующие командам на bf.

2019-04-29 15:33 UTC, Tiltedprogrammer commented on Task02/review
> +   - задействует метод print класса java/io/PrintStream
а еще между ними подготавливает стек, т.е. кладет сначала туда ссылку на массив памяти, потом кладет туда значение, которое указывает на текущую клетку, а потом кладет на верхушку стека значение из текущей клетки (из массива по индексу), метод соотвественно делает `print`.

2019-04-29 15:33 UTC, Tiltedprogrammer commented on Task02/review
> +  методов генерирует исключение)
Странно, что он ничего не генерирует, если не найдет `main`.

2019-04-29 15:33 UTC, Tiltedprogrammer commented on Task02/review
> +  программы.
А каким образом этот `out` получается?

2019-04-29 15:33 UTC, Tiltedprogrammer commented on Task02/review
> +Соответствие стайлгайду
В тестах еще обычно методы содержат слово `Test`

2019-05-01 22:25 UTC, EgorkaKulikov commented
Я выкладываю, надеюсь, весь указанный фмдюэк дошёл до автора

2019-05-01 22:25 UTC, merged