Added Task01 with tests
EgorkaKulikov/spbu-se2019-spring pull request #3
Opened 2019-03-09 13:23 UTC by foxyelite

2019-03-12 20:30 UTC, EgorkaKulikov requested changes

2019-03-12 20:30 UTC, EgorkaKulikov commented on Task01/src/main.kt
> +const val INF = Int.MAX_VALUE
То есть при чтении кода становится понятнее?

2019-03-12 20:30 UTC, EgorkaKulikov commented on Task01/src/main.kt
> +            if (beginVertex > endVertex) {
А можно, кажется, просто генерировать в нужном диапазоне
fun nextInt(from: Int, until: Int): Int

2019-03-12 20:30 UTC, EgorkaKulikov commented on Task01/src/main.kt
> +        println("Do you want to know the number of vertices of the graph? yes/no")
Предлагаю запросившему статистику по графу вывести её без лишних вопросов

2019-03-12 20:30 UTC, EgorkaKulikov commented on Task01/src/main.kt
> +    fun printGraphStatistics(K : Int = 0) {
Значение по умолчанию здесь выглядит странно...

2019-03-12 20:30 UTC, EgorkaKulikov commented on Task01/src/main.kt
> +                        print("${path[j]}${if (j == path.size - 1) "\n" else " - "}")
на мой взгляд, перебор

2019-03-12 20:30 UTC, EgorkaKulikov commented on Task01/src/main.kt
> +
Код очень простынный

2019-03-12 20:30 UTC, EgorkaKulikov commented on Task01/tests/ShortestPath.kt
> +
Скорее всего, это было немного избыточно, обсудим... Ну и нужно обсудить, почему от юнит-теста в классическом понимании здесь один assert

2019-03-12 20:30 UTC, EgorkaKulikov commented on Task01/tests/ShortestPath.kt
> +                    val lenDijkstra: Array<Int> = graph.getDijkstraShortestPath(K).first
.first - это очень не очень
 Но почему-то в Котлине не поддержали именованные кортежи... Надо бы почитать, почему. Хотя в С# до стандарта 7.0 их тоже не было, и жили. Но так всё равно не писали.

Но вывернуться в любом случае можно, хотя бы здесь какие-то варианты, не уверен, что хорошие только https://stackoverflow.com/questions/48133381/how-to-name-components-of-a-pair

2019-03-16 21:45 UTC, EgorkaKulikov commented
Нужно переименовать в Task01_Abzalov

2019-03-17 16:47 UTC, foxyelite commented on Task01/src/main.kt
> +
Не могли бы вы объяснить значение словосочетания "простынный код" и указать явно в чем проблема.

2019-03-17 20:37 UTC, EgorkaKulikov commented on Task01/src/main.kt
> +
Код, в котором логические элементы не разделены пробелами и отступами. Стоит посмотреть рекомендации языка/среды разработки на этот счёт.

2019-03-17 20:40 UTC, EgorkaKulikov approved these changes

2019-03-26 19:19 UTC, merged