Task02_Abzalov
EgorkaKulikov/spbu-se2019-spring pull request #31
Opened 2019-04-15 18:11 UTC by foxyelite

2019-04-16 21:01 UTC, vkutuev requested changes
Задание по сути не сделано. 
1) Надо проанализировать решение, для каждого класса описать его роль в работе программы (что он делает), формальную информацию о нём. Для методов класса нужно рассказать о функциональности (что делает?), и об особенностях реализации (как делает?). Также надо рассказать, как классы взаимосвязаны, как взаимодействуют, чтобы описать структуру программы.
2) Надо разобрать комментарии. (Все обозревать точно не надо. Мне кажется, можно разбить на блоки общей тематики и сделать обзор блока)
3) Пункт не расписан, предложите конкретные решения, расскажите, чем они помогут. (Желательно протестировать их хотя бы на себе)

2019-04-16 21:01 UTC, KutuevVladimir commented on Task02/Task02.txt
> +            setupJums():
Jumps

2019-04-18 21:33 UTC, EgorkaKulikov requested changes
Согласен с Вовой по всем пунктам. Это набросок к будущему ревью, но не ревью.

2019-04-20 20:20 UTC, foxyelite commented on Task02/Task02.txt
> +            setupJums():
Исправлено

2019-04-20 20:25 UTC, foxyelite commented
Если кто-нибудь дополнительно объяснит что нужно сделать, чтобы в Intellij заработал [BrainGenerator.kt] буду очень признателен.

2019-04-20 21:36 UTC, Tiltedprogrammer commented
Знать бы еще в чем у вас конкретно проблема, но возможно нужно добавить библиотеку в gardle
[как тут](https://github.com/anna-marina/assignments/blob/08afe112eac02cbb3d5f3d844ded634c836f0519/build.gradle)

2019-04-22 19:07 UTC, foxyelite commented
На данный момент, можно считать, что мое ревью готово. Прошу его проверить и добавить замечания, если таковые будут.

2019-04-28 19:05 UTC, merged