Task01
EgorkaKulikov/spbu-se2019-spring pull request #32
Opened 2019-04-15 19:28 UTC by Duletov

Task 1 complete

2019-04-16 17:22 UTC, NikitaMishin requested changes
необходим ряд изменений:
1) замечания по оформлению кода
2) магические константы
3) в дейсктре затесалась ошибка
4) в беллмане необходимо перечитать алгоритм и внести изменения

2019-04-16 17:22 UTC, NikitaMishin commented on Task01/Task01.kt
> +fun Stats(n: Int, m: Int, graf: Array<Array<Int>>) {
https://kotlinlang.org/docs/reference/coding-conventions.html есть определенные соглашения насчет стайлинга кода. Можно использовать то, что больше нравится, но придерживаться чего-то одного.
В данном случае, у тебя вперемешку названия функций то с большой , то с маленькой буквы

2019-04-16 17:22 UTC, NikitaMishin commented on Task01/Task01.kt
> +fun Create(n: Int, m: Int): Array<Array<Int>> {
думаю, название функции createGraph будет более содержательным. 
+ нужно нормальное название входных параметров (не олимп прога с i,j,k,l,m), чтобы человек мог взглянуть на код и сразу понять, что требуется. Тут вообще непонятно, сперва думал, что это кол-во строк и столбцов)

2019-04-16 17:22 UTC, NikitaMishin commented on Task01/Task01.kt
> +val MAX_LENGTH = 101
нужно более корректное название, т.к что-нибудь связанное с дистанией или стоимостью (cost, distance).

2019-04-16 17:22 UTC, NikitaMishin commented on Task01/Task01.kt
> +                rand1 = (0..(n - 2)).random()
к комментарию выше, rand_from, rand_to или from и to, так становится намного понятнее

2019-04-16 17:22 UTC, NikitaMishin commented on Task01/Task01.kt
> +                rand1 = (0..(n - 2)).random()
и почему такой странный рандом?

2019-04-16 17:22 UTC, NikitaMishin commented on Task01/Task01.kt
> +    var trigger = false
аналогично , более содержательное название

2019-04-16 17:22 UTC, NikitaMishin commented on Task01/Task01.kt
> +fun Stats(n: Int, m: Int, graf: Array<Array<Int>>) {
плюса замечания насчет названий параметров и graph* (не graf)

2019-04-16 17:22 UTC, NikitaMishin commented on Task01/Task01.kt
> +            if (distance[curVrtx] == MAX_LENGTH + 1) {
что-то в этой строчке очень плохое, что ломает весь алгоритм

2019-04-16 17:22 UTC, NikitaMishin commented on Task01/Task01.kt
> +    val distance = Array(n){MAX_LENGTH*1001}
что за магическая константа?  max_length*1001 - это ведь INF ?

2019-04-16 17:22 UTC, NikitaMishin commented on Task01/Task01.kt
> +    val off = Array(n){false}
название не интуитивное, мб что-нибудь в духе used ?

2019-04-16 17:22 UTC, NikitaMishin commented on Task01/Task01.kt
> +            for (j in 0 until n) {
to ведь более понятное название?)

2019-04-16 17:22 UTC, NikitaMishin commented on Task01/Task01.kt
> +    val distance: Array<Int> = Array(graph.size){MAX_LENGTH*1001}
та же магическая константа.

2019-04-16 17:22 UTC, NikitaMishin commented on Task01/Task01.kt
> +                if (graph[curVrtx][j] != 0) {
а у нас не может быть пути длины ноль из какой-то вершины в какую-то?

2019-04-16 17:22 UTC, NikitaMishin commented on Task01/Task01.kt
> +    }while(!stop)
зачем здесь while ? алгоритму достаточно ведь n-1 фазы алгоритма.
Плюс для данного алгоритма невыгодно хранить матрицей смежности. Намного выгоднее представлять граф в виде одного списка всех ребер или же списка смежности. Можете почитать на вики, итмо или emaxx

2019-04-16 17:22 UTC, NikitaMishin commented on Task01/Task01.kt
> +    if (n>1000 || m>100000 || n<=0 || m<0){
опять магические константы

2019-04-16 17:46 UTC, KutuevVladimir commented on Task01/Task01.kt
> +    }while(!stop)
While выгоднее, он может закончиться быстрее, чем за n + 1 шаг.
Как хранить граф дело разработчика, Но в решении не алгоритм Форда-Беллмана: асимптотика решения |V|^3, а должно быть |V|*|E|. Подсказка: 
`for(i in 0 until graph.size) {
            for(j in 0 until graph.size){`
выполняется каждый раз, достаточно сделать это 1 раз для вычисления списка рёбер.

2019-04-16 18:08 UTC, Duletov commented on Task01/Task01.kt
> +fun Create(n: Int, m: Int): Array<Array<Int>> {
Входные названия параметров n и m взяты из условия задачи и являются вполне значимыми и однозначными

2019-04-16 18:08 UTC, Duletov commented on Task01/Task01.kt
> +    if (n>1000 || m>100000 || n<=0 || m<0){
Магические константы взяты из условий задачи. Не знаю, что с ними делать

2019-04-16 18:08 UTC, Duletov commented on Task01/Task01.kt
> +                rand1 = (0..(n - 2)).random()
С рандомом всё хорошо, потому что иначе останется только вершина n-1 для создания рёбер

2019-04-16 18:15 UTC, NikitaMishin commented on Task01/Task01.kt
> +    if (n>1000 || m>100000 || n<=0 || m<0){
ну, как минимум, вынести в  определение класса или как константы(как с MIN_LENGTH) в файле

2019-04-16 18:24 UTC, NikitaMishin commented on Task01/Task01.kt
> +fun Create(n: Int, m: Int): Array<Array<Int>> {
понятно, что они взяты из задачи. Представьте ситуацию, когда документации (условия задачи) для данной функции нет, тогда с меньшей вероятностью придется смотреть исходники программы и понимать, что функция требует на вход и что параметры означают. Например,  
fun create(numVertices:Int,numEdges:Int) или fun create(vertices:Int,edges:Int) выглядит лучше , чем ваша , т.к понятнее, что функция требует на свой вход. А что такое n и m? Непонятно(

2019-04-16 18:42 UTC, NikitaMishin commented on Task01/Task01.kt
> +                rand1 = (0..(n - 2)).random()
первый for  - это создаем m ребер
почему мы не можем просто сделать 
randomVertex1 = (0..n-1).random()
randomVertex2 = (0..n-1).random()
ну и учитывать случай, когда они равны? Вопрос был к этому

2019-04-16 18:45 UTC, vkutuev requested changes

2019-04-16 18:45 UTC, KutuevVladimir commented on Task01/Task01.kt
>      }
Выравнивание! (Глядя на код, я думал, что он не компилится)

2019-04-16 18:45 UTC, KutuevVladimir commented on Task01/Task01.kt
> +    var k = readLine()!!.toInt()
Надо избегать использования `!!`. Я первым же запуском опрокинул код с NPE (причём абсолютно случайно). Лучше проверять на `null`, и если оно оказалось таковым, то либо вывести сообщение и продолжить работу (ждать пока не получим валидный вход) или завершить программу с соответствующим сообщением, либо бросить какое-то осмысленное исключение.

2019-04-16 18:45 UTC, NikitaMishin commented on Task01/Task01.kt
> -            if (distance[curVrtx] == MAX_LENGTH + 1) {
здесь было замечание насчет того, что проверка ведь должна быть не с MAX_DISTANCE,  а с  INFINITY

2019-04-16 18:51 UTC, NikitaMishin commented on Task01/Task01.kt
>      }
в intelij idea  можно легко выровнять код (Ctrl+Shift+Alt+L либо через code + reformat code), если забываете сами выравнивать

2019-04-16 21:31 UTC, KutuevVladimir commented on Task01/Task01.kt
> +            for (j in 0 until n) {
В целом я бы советовал для алгоритмов принятое для этого алгоритма именование. (Например по книжке Кормена)

2019-04-17 19:14 UTC, Duletov commented on Task01/Task01.kt
> +    var k = readLine()!!.toInt()
Добавил проверку

2019-04-17 19:15 UTC, Duletov commented on Task01/Task01.kt
> +    }while(!stop)
Переделал алгоритм. Теперь работает корректно?

2019-04-17 22:23 UTC, vkutuev requested changes
Замечание по `!!` надо бы исправить. 
В остальном мне нравится.
Ещё маленький комментарий: аккуратнее с выводом текста на русском (любом локальном языке), я просто такой вывод получил: 
`? ?????:
1 ??????
????? ???`

2019-04-17 22:23 UTC, KutuevVladimir commented on Task01/Task01.kt
> +        k = readLine()!!.toInt()
Я говорил конкретно про `!!`. Использование такой штуки легко приводит к бросанию NullPointerException (конкретно `KotlinNullPointerException`). Kotlin специально дизайнили так, чтобы уменьшить число NPE. Применение `!!` к некоторому значению бросает NPE, если значение `null`, поэтому его рекомендуют использовать в условиях крайней уверенности, что значение не `null`.
Мои предложения по исправлению:

- убрать в этом месте `!!`. Тогда при попытке каста полетит `NumberFormatException`, который как раз отлавливается. Но подобным образом не всегда можно поступать, вдруг функция, в которую передаётся значение на получение `null` бросит NPE. Т.к Kotlin хорошо миксуется с JVM, то на такие функции/методы легко нарваться.

- Проверить `readLine()` на `null` и как-то отреагировать на это. Например так:
`k = readLine()?.toInt() ?: {
        println("Data is incorrect")
        0
    }()`
или так:
`val inputData = readLine()
    var data: String = ""
    if (inputData != null) {
        data = inputData.toString()
    } 
    else {
    	println("No number of vertexes and number of edges")    
    }`

2019-04-17 22:23 UTC, KutuevVladimir commented on Task01/Task01.kt
> +    val numEdge = data.substringAfter(' ').toInt()
В прошлый раз не заметил, но `data.substringBefore(' ').toInt()` и `data.substringAfter(' ').toInt()` бросают `NumberFormatException` (`null` пытаемся сделать интом), если в строке нет пробелов. Вообще лучше проверять, удался ли каст, но это скорее рекомендация. 
Вообще рекомендую проверять на null всё, что может им оказаться, но не должно.
(Тут не обязательно исправлять)

2019-04-17 22:34 UTC, KutuevVladimir commented on Task01/Task01.kt
> +                distance[queue[i].end] = distance[queue[i].start] + queue[i].dist
Рекомендую для обхода коллекций использовать `.forEach`, когда это возможно. Оно отражает логику того, что происходит: хотим поэлементно пройтись по коллекции, и обрабатывать только текущий элемент.

2019-04-17 23:52 UTC, Duletov commented on Task01/Task01.kt
> +        k = readLine()!!.toInt()
Просто убрать не позволяет котлин.  А вот второй вариант стоит попробовать, выглядит хорошо. Правда на такую формулировку { println("Data is incorrect") 0 }() идея ругается, поэтому просто null в -1 буду переводить, результат то тот же

2019-04-18 21:10 UTC, EgorkaKulikov commented on Task01/Task01.kt
> +                rand1 = (0..(n - 2)).random()
Почему-то было массовое увлечение пробеганием всех пар индексов и дальнейшей проверкой, не получилось ли равенства. Когда я предлагал совершенно аналогичный фикс, мне даже какие-то аргументы против приводили...

2019-04-18 21:14 UTC, EgorkaKulikov commented on Task01/Task01.kt
> +    var k = readLine()!!.toInt()
А разве в новой реализации у нас есть какой-то шанс действительно упасть по тому исключению, которое пытаемся ловить?

2019-04-18 21:16 UTC, EgorkaKulikov commented on Task01/Task01.kt
> +    var k = readLine()!!.toInt()
Ну да, и вот Вова ниже предлагает решение, там вроде исключения нет.

2019-04-18 21:20 UTC, EgorkaKulikov commented on Task01/Task01.kt
> +                distance[queue[i].end] = distance[queue[i].start] + queue[i].dist
Согласен, но на исправлении не настаиваю. Кстати, а почему массив рёбер назван queue, если никаких признаков очереди он в себе не несёт?

2019-04-18 21:23 UTC, EgorkaKulikov commented on Task01/Task01.kt
> +    val numEdge = data.substringAfter(' ').toInt()
Вот, школа Белкасофта даром не проходит, Вова помнит, сколько там было бесконечных NullReferenceException в багах. А всё из-за того, что криворукие программисты не писали подобные проверки. И ещё решарпером пользоваться ленились. А он и подобные средства очень годно помогают отлавлись потенциальные null reference, поскольку это, в отличие от поиска каких-нибудь гонок потоков, часто очень просто.

2019-04-18 21:24 UTC, EgorkaKulikov commented
Осталось несколько небольших замечаний.

2019-04-18 21:26 UTC, Duletov commented on Task01/Task01.kt
> +                distance[queue[i].end] = distance[queue[i].start] + queue[i].dist
Да, название неправильное. Думаю, listEdges было бы лучше

2019-04-18 21:50 UTC, Duletov commented on Task01/Task01.kt
> +    val numEdge = data.substringAfter(' ').toInt()
При введении двух чисел без пробела он вставляет получившееся значение в обе переменные и я не знаю как это отловить, поэтому поставил только проверку на корректность данных.

2019-04-20 10:02 UTC, vkutuev approved these changes

2019-04-20 10:51 UTC, NikitaMishin approved these changes

2019-04-20 12:23 UTC, Tiltedprogrammer commented on Task01/Task01.kt
> +    val numEdge = data.substringAfter(' ').toInt()
ну в таком случае можно все то же самое делать с методом [split](https://kotlinlang.org/api/latest/jvm/stdlib/kotlin.text/split.html), тогда можно будет проверить сколько чисел пришло на вход.

2019-04-21 11:08 UTC, EgorkaKulikov approved these changes

2019-04-21 11:08 UTC, merged