Task03&Task04_Smirnov
EgorkaKulikov/spbu-se2019-spring pull request #33
Opened 2019-04-17 14:09 UTC by osmirnovv

2019-05-07 21:11 UTC, vkutuev requested changes
Очень странная структура проекта: узлы, деревья и балансировщик. Хочется, чтобы структура пакетов отражала декомпозицию понятий (что из чего состоит, в каком контексте существует). Узел всё-таки не существует без дерева, это его составная часть, а балансировщик - инструмент, который используется только деревом.
Именование пакетов не соответствует принятому code style: 
> Names of packages are always lower case and do not use underscores.
> Using multi-word names is generally discouraged, but if you do need to use multiple words, you can either simply concatenate them together or use camel humps.

2019-05-07 21:11 UTC, vkutuev commented on src/test/kotlin/SearchTest.kt
> +            assertEquals(actualTree[key], expectedAnswers[key])
Перепутаны expected и actual параметры assert'а

2019-05-07 21:11 UTC, vkutuev commented on src/main/kotlin/Trees/Tree.kt
> +                nextNode = tree.getMinNode(currentNode?.right)!!
!! - зло, использовать надо, только при 100% уверенности, что значение не null. Советую заменить на `nextNode = tree.getMinNode(currentNode?.right) ?: throw NullPointerException("There are no more nodes in the tree")`, либо определить собственное исключение, говорящее больше об ошибке.

2019-05-07 21:11 UTC, vkutuev commented on src/main/kotlin/Trees/Tree.kt
> +            return prevNode!!
Опять проблема с !! . При вызове next() при hasNext() == false бросит NPE, а по документации должен бросать NoSuchElementException.
Советую переписать как-то так `return prevNode ?: throw NoSuchElementException()`

2019-05-07 21:11 UTC, vkutuev commented on src/test/kotlin/IterationTest.kt
> +    fun iterateEmpty() {
Надо бы ещё посмотреть, что при вызове `actualTree.iterator().next()` будет выброшено нужное исключение

2019-05-07 21:11 UTC, vkutuev commented on src/test/kotlin/IterationTest.kt
> +class BinarySearchTreeIterationTest {
Все тесты основаны на свойстве keys, которое проходит по всем элементам через forEach. Но итератор можно получить методом iterator() и ковырять руками, поэтому надо и эту функциональность протестировать.

2019-05-07 21:11 UTC, vkutuev commented on src/main/kotlin/Trees/Tree.kt
> +    private inner class TreeIterator(private val tree: Tree<K, V, NodeType>) : Iterator<NodeType> {
Зачем передавать этому итератору `tree: Tree`? Это внутренний класс, он видит все свойства и методы.
Тут либо убрать `inner`, либо не передавать дерево в итератор. Мне кажется, что второй вариант элегантнее.

2019-05-07 21:11 UTC, vkutuev commented on src/main/kotlin/Nodes/Node.kt
> +abstract class Node<K: Comparable<K>, V, NodeType: Node<K, V, NodeType>>(var key: K, var value: V) {
Насколько я понял, в задании ничего не обговаривалось насчёт того, что хранится в дереве. Здесь в дереве хранится KeyValuePair. Это ошибка проектирования.

2019-05-07 21:11 UTC, vkutuev commented on src/main/kotlin/Trees/Tree.kt
> +    operator fun get(key: K): V? {
У произвольного дерева не обязаны выполняться инварианты дерева поиска, поэтому поиск по абстрактному дереву так делать некорректно.

2019-05-07 21:11 UTC, vkutuev commented on src/main/kotlin/NodeBalancer.kt
> +internal class NodeBalancer<K: Comparable<K>, V, NodeType: Node<K, V, NodeType>> {
С этим классом есть определённая проблема: он не имеет внутреннего состояния, ни от кого не наследуется, никто от него не наследуется (и идейно вряд ли можно придумать класс-наследник). Т.е похоже, что его методы - статические и NodeBalancer - некоторые utils. Но т.к все его методы взаимодействую с узлами, используют их внутреннее устройство, то возникает мысль, что все эти методы - методы узла (причём произвольного узла), тем более у специфичных узлов методы вращения просто вызывают данные. Это также поможет сделать protected все свойства отвечающие за родственников (инкапсуляция).
Если я не прав, приведите примеры, почему для вращения узлов требуется сторонний агент. Но именование его в любом случае надо менять, он за баланс не отвечает, он просто вращает вершины.

2019-05-07 21:11 UTC, vkutuev commented on src/main/kotlin/Trees/Tree.kt
> +    internal open var root: NodeType? = null
Сейчас узлы несут очень много информации о своём внутреннем устройстве, поэтому нужно либо спрятать корень дерева (сделать protected), либо спрятать структуру узлов.

2019-05-07 21:11 UTC, KutuevVladimir commented on src/main/kotlin/Trees/Tree.kt
> +    private inner class TreeIterator(private val tree: Tree<K, V, NodeType>) : Iterator<NodeType> {
Тут тоже порос по тому, что итератор выдаёт наружу узел. Поэтому либо итератор должен возвращать то, что лежит в узле, либо надо спрятать структуру узла.

2019-05-07 21:11 UTC, KutuevVladimir commented on src/main/kotlin/Nodes/RedBlackNode.kt
> +    // Using Strategy pattern
Т.к стратегия одна, и чётко определяется, то на одноимённый паттерн это не тянет.

2019-05-16 22:28 UTC, EgorkaKulikov commented
@SmirnovOleg Олег, чего как тут? Ни ответов, ни фиксов

2019-05-17 19:52 UTC, SmirnovOleg commented on src/main/kotlin/Trees/Tree.kt
> +                nextNode = tree.getMinNode(currentNode?.right)!!
В данном случае использование !! оправдано: из-за условного перехода сверху currentNode?.right точно не null, а функция getMinNode() вернет в худшем случае переданную ей вершину (иначе пойдет влево по дереву дальше). Т.е. null'а там не будет.

2019-05-17 20:06 UTC, SmirnovOleg commented on src/main/kotlin/Nodes/Node.kt
> +abstract class Node<K: Comparable<K>, V, NodeType: Node<K, V, NodeType>>(var key: K, var value: V) {
Здесь хотелось бы подробнее, в чем, собственно, ошибка? "Хранятся" в дереве ключи и значения, так что проблема скорее в кривой передаче generics)
Можно было обойтись без этого, и постоянно писать касты от одних нод к другим, либо вообще не устанавливать между ними связи наследованием, но мы увидели именно такой путь решения проблемы. Плюс, такое определение типов происходит только на уровне абстракции, в конкретном же представлении все четко (вроде AVLNode<K, V>)
В любом случае, третий параметр подразумевает не данные, а легковесную информацию о типе вершины, так что глобальной ошибки тут не вижу. Если не прав, объясните.

2019-05-17 20:09 UTC, SmirnovOleg commented on src/main/kotlin/Trees/Tree.kt
> +    operator fun get(key: K): V? {
Переименовал в AbstractBinarySearchTree, но даже так возникает тавтология с модификатором abstract у класса; убирая же его, получаем конфликт имен с другим конкретным классом наследником, ну а писать что-то вроде "BinarySearchTree : BSTree" уж совсем извращение. Так что если есть варианты, как назвать лучше, я был бы рад их услышать)

2019-05-17 20:29 UTC, SmirnovOleg commented on src/main/kotlin/NodeBalancer.kt
> +internal class NodeBalancer<K: Comparable<K>, V, NodeType: Node<K, V, NodeType>> {
Добавил companion object, теперь отдельный экземпляр класса не создается, и по сути это правда стало utils.
Говоря о таком подходе в целом, путь решения, конечно, мог быть следующим: добавить отдельный класс с балансирующимися нодами, от него унаследовать RedBlackNode и AVLNode (именно класс, а не интерфейс, чтобы не дублировать код). Но до того, как NodeRotator стал, по сути, статическим, он подключался с помощью композиции, которая, насколько я знаю, всегда предпочтительнее наследования. Получается, это просто иной способ не дублировать код для вращения вершин. К вопросу о том, что он ничего не наследует и наследников у него нет - да, но что в этом такого? Разве все классы проекта должны быть связаны наследованием? Слабо связанные структуры более гибкие, их легче изменять. 
Если уже совсем опускаться до идейно-холиварного контекста, мне лично кажется, что так как поворот вершины задействует ее соседей (а большой даже соседей соседей), делать поворот методом вершины не совсем правильно, но помещать его в дерево тоже в этом смысле оверкилл, поэтому создание вспомогательного агента, вращающего вершины, - компромиссная идея.

2019-05-17 20:37 UTC, SmirnovOleg commented
Замечания по коду поправил, теперь в нодах больше internal, итератор умеет кидать exceptions. Также добавил командных тестов на equals и итератор. С NodeRotator вопрос сложный, мне все же нравится его идея, и я как-то не вижу конкретных причин, зачем его переделывать. 

Логи тестов тоже добавлены. @EgorkaKulikov , @KutuevVladimir , жду замечаний/указаний.

2019-05-18 16:59 UTC, KutuevVladimir commented on src/main/kotlin/Nodes/Node.kt
> +abstract class Node<K: Comparable<K>, V, NodeType: Node<K, V, NodeType>>(var key: K, var value: V) {
Ошибка в том, что я не хочу к значению делать ключ, я хочу в дереве хранить числа или людей, или дома (если умею их сравнивать), не хочу ключи для них придумывать. А ваша реализация не позволяет этого делать.

2019-05-18 17:05 UTC, KutuevVladimir commented on src/main/kotlin/Trees/Tree.kt
> +    operator fun get(key: K): V? {
Почему AbstractBinarySearchTree будет тавтология? Мне кажется, что это вполне нормально, более того, глядя на название класса, видно, что он абстрактный без заглядывания в его исходник. 
Но если хотите оставить Tree, то либо get должен просто тупо обходить дерево пока не найдёт нужное значение, либо реализацию для get не писать.

2019-05-18 19:39 UTC, SmirnovOleg commented on src/main/kotlin/Nodes/Node.kt
> +abstract class Node<K: Comparable<K>, V, NodeType: Node<K, V, NodeType>>(var key: K, var value: V) {
Возможно, мы по-разному понимаем задачу, раз условия все же четкого не было) 
Здесь специально оставлена возможность самостоятельно выбирать ключи, и сеттер сделан оператором как раз под это (tree[key] = value), т.е. реализуется интерфейс ассоциативного массива. Аналоги - плюсовый map и TreeMap в Java.

2019-05-19 10:00 UTC, EgorkaKulikov commented on src/main/kotlin/Nodes/Node.kt
> +abstract class Node<K: Comparable<K>, V, NodeType: Node<K, V, NodeType>>(var key: K, var value: V) {
@SmirnovOleg речь здесь идёт о том, что в принципе существуют и вполне себе используются штуки наподобие TreeSet, где нет ключей, а просто значения являются IComparable объектами. Моя ошибка заключается в том, что я не донёс до группы мысль, что такое бывает, а также до проверяющих, что мы смотрим на дерево как на ассоциативный массив. Прошу прощения.

2019-05-19 21:55 UTC, vkutuev requested changes
В целом мне уже нравится. С некоторыми решениями в рамках задачи я не очень согласен, но в субботу выслушаю аргументы, задам вопросы, надеюсь, что моё мнение поменяется.
Так что обнаружил 1 грубую проблему (см. ниже), жду её исправления (уж очень хочется самому тесты прогнать)
Еще комментарий по тестам: желательно в тесте print'ом выводить какую-то информацию, поясняющую тест, чтобы при падении теста не получать сухое: "Ожидалось 100, фактически 103", но это не супер критично

2019-05-19 21:55 UTC, KutuevVladimir commented on build.gradle.kts
> -    testCompile("junit", "junit", "4.12")
Верните Gradle! Он очень нужен в репозитории

2019-05-19 22:18 UTC, EgorkaKulikov commented
> Еще комментарий по тестам: желательно в тесте print'ом выводить какую-то информацию, поясняющую тест, чтобы при падении теста не получать сухое: "Ожидалось 100, фактически 103", но это не супер критично

Эх, у нас на работе тесты обычно именно так и падают. Не очень удобно, конечно, но жить можно, в принципе, поскольку по-хорошему тесты должны падать не слишком часто.

2019-05-21 17:38 UTC, merged