Task02_Pogozhelskaya
EgorkaKulikov/spbu-se2019-spring pull request #35
Opened 2019-04-22 19:47 UTC by Pogozhelskaya

2019-04-26 17:28 UTC, Tiltedprogrammer requested changes
Неплохое ревью, однако надо пару мест поправить-расширить, может придумаете какими еще способами можно улучшить имеющийся код. (Предложите интерфейс из замечания, например.)

2019-04-26 17:28 UTC, Tiltedprogrammer commented on Task02/CodeReview.txt
> +		Метод interpete: основной метод класса. Принимает строку кода на Brainfuck, далее каждой команде на Brainfuck сопоставляется ее эквивалент(в том числе осуществляется частичная проверка на некоррект
> если циклы построены неправильно

На первый взгляд, ошибка возникает только если `]` скобок больше чем `[`. Так ли это? И если так, то какой-нибудь подсчет скобок мог бы покрывать больше случаев некорректного входа.

2019-04-26 17:28 UTC, Tiltedprogrammer commented on Task02/CodeReview.txt
> +		Метод interpete: основной метод класса. Принимает строку кода на Brainfuck, далее каждой команде на Brainfuck сопоставляется ее эквивалент(в том числе осуществляется частичная проверка на некоррект
> последовательно печатаются проинтерпретированные символы, если в коде на Brainfuck была соответствующая команда

печатается только содержимое клеток при команде `.`, при условии, что флаг для вывода в stdout установен в `true`. Хотя, возможно, вы имели в виду что-то другое.

2019-04-26 17:28 UTC, Tiltedprogrammer commented on Task02/CodeReview.txt
> +		Метод toByteCode: метод берущий на себя основную функциональность, возвращает байт-код Java, внутри используются классы CodeNode и CodeWriter, с помощью которых класс представляется в виде массива
Тут хотелось бы поподробней про то как хотя бы идейно устроен метод `toByteCode`. Там, например, инициализируется локальная переменная в java class'е, которая указывает на текущую ячейку. Ну и много чего еще происходит.

2019-04-26 17:28 UTC, Tiltedprogrammer commented on Task02/CodeReview.txt
> +		nums – массив кодов символов, len – длина входной строки, далее с помощью полученной информации представлен сам алгоритм конвертирования в код на Brainfuck.
Тут хотя бы в двух словах надо про логику используемого алгоритма для получения программы на bf. Потому что как иначе можно предложить изменения по улучшению кода?

2019-04-26 17:28 UTC, Tiltedprogrammer commented on Task02/CodeReview.txt
> +		Метод toByteCode: большое количество “неговорящих” названий переменных(cn, mn0, lbls и др.), из-за чего очень усложняется читаемость кода для стороннего ревьюрера.
ну названия вполне говорящие на самом деле, `cn - ClassNode`, `lbls` - labels, но согласен, что читать код, где заполняется джава-класс трудно.

2019-04-26 17:28 UTC, Tiltedprogrammer commented on Task02/CodeReview.txt
> +
в паре мест еще можно заменить циклы на `forEach` или `map`

2019-04-26 17:28 UTC, Tiltedprogrammer commented on Task02/CodeReview.txt
> +	Pull request состоит из следующих файлов: asciiToBrainfuck.kt, bfToJvmCompiler.kt, brainfuckInterpeter.kt, а также тестов к ним.
Про тесты вы, кстати, зря не написали. Там есть тест `incorrectCodeTest()`, который идеологически не очень правильно написан. В `JUnit` есть [способы](https://github.com/junit-team/junit4/wiki/exception-testing) проверить, что метод бросит нужное исключение без использования `try catch` в тесте и тем более `assert fail`

2019-04-26 17:28 UTC, Tiltedprogrammer commented on Task02/CodeReview.txt
> +		return res?.toString() ?: null → return res?.toString(), по стандарту Kotlin если res == null, то ничего не произойдет.
> то ничего не произойдет.

Не совсем ничего, вернется `null`

2019-04-28 19:06 UTC, EgorkaKulikov commented
Аппрува нет, ответов и исправлений тоже, жду.

2019-05-02 14:41 UTC, Tiltedprogrammer approved these changes
Теперь, конечно же, апрув. Однако, все еще интересно было бы увидеть (в смысле написанного предложения о том, как бы вы реализовали этот момент) ваше решение для замечания про единообразный интерфейс.

2019-05-03 10:06 UTC, merged