Task03_Privalihin
EgorkaKulikov/spbu-se2019-spring pull request #36
Opened 2019-04-23 19:22 UTC by AlekseiPrivalihin

Iterators are not yet implemented, only the most basic tests are present. Work in progress

2019-05-02 21:23 UTC, NikitaMishin commented on Privalihin/Task03/src/BinarySearchTree.kt
> +        var left: Node? = null
можно вынести все благополучно в конструктор (хуже точно не станет, меньше кода) и меньше дублирования кода ( в частности, у вас просто идет копирование параметров, хотя можно сразу написать в конструкторе var)

2019-05-02 21:39 UTC, NikitaMishin commented on Privalihin/Task03/src/BinarySearchTree.kt
> +    public open inner class Node(_value: T, _key: K, _parent: Node?) {
а зачем нам inner? почему нода должна знать о дереве? необходимо и верно ли это?

2019-05-02 21:42 UTC, NikitaMishin commented on Privalihin/Task03/src/BinarySearchTree.kt
> +    public open inner class Node(_value: T, _key: K, _parent: Node?) {
и какой-то у вас неинтуитивный порядок key,value. Ожидаешь, что вставка и инициализация такого рода вещей будет в духе fun insert(key,value) (имхо).(Начал тестить и сперва падало, а все из-за неинтуитивного порядка)

2019-05-02 21:46 UTC, NikitaMishin commented on Privalihin/Task03/src/BinarySearchTree.kt
> +    public open inner class Node(_value: T, _key: K, _parent: Node?) {
1)На  мой взгляд неинтуитивный порядок value,key. При вставке и инициализации ожидаешь key, а потом value.
2) Зачем inner? нужно ли, чтобы узел знал о дереве и имел доступ к его полям?
3) зачем лишнее копирование, ведь можно инициализацию перенести в конструктор и избежать лишнего копирования

2019-05-02 21:47 UTC, NikitaMishin commented on Privalihin/Task03/src/BinarySearchTree.kt
> +    protected open var root: Node? = null
зачем здесь open модификатор?

2019-05-02 21:57 UTC, NikitaMishin commented on Privalihin/Task03/src/BinarySearchTree.kt
> +                    curNode.right = createNode(value, key, curNode)
здесь можно вместо if использовать when, получится более цельно
when {
curNode.key == key => {
}
curNode.key < key => {
}
curNode.key > key => {
}
}

2019-05-02 21:57 UTC, NikitaMishin commented on Privalihin/Task03/src/RBTree.kt
> +        // Maybe I should replace it with an enum class
согласен)

2019-05-02 22:17 UTC, NikitaMishin requested changes
2) Есть пара незначительных недочетов
3) По поводу архитектуры не буду высказываться (в частности, огромное кол-во приведений сильно настораживает )
4) Необходимо 
а) Принтер для обычного бинарного дерева поиска (сейчас реализация отсутствует)
б) Нормальный вывод дерева в консоль (я сломал глаза и другие тоже, от Егора пламенный привет:) ). В частности не смог удостовериться, удовлетворяют ли дервья своим свойствам
в) тесты (в их рамках очень советую реализовать для красно-черного дерева проверку, что оно удовлетворяет всем свостйвам( тестовая или внутрення фукция isRedBlackTree, аналогично для авл дерева)). Готов апрувнуть, когда появится оставшаяся часть тестов (isRedBlackTree, isAvlTree - для того, чтобы показать, что деревья удовлетворяют заявленным свойстам) и будет нормальный вывод
 1) А, в общем, гуд, мне понравилось, чисто написано
Ну и автор может ,ради интереса,(для себя) написать стресс-тесты и проверить насколько обычное бинарное дерево поиска может проиграть в скорости своим аналогам

2019-05-02 22:17 UTC, NikitaMishin commented on Privalihin/Task03/src/AVLTree.kt
> +        var flag = 0
необходимо более содержательное название переменной

2019-05-02 22:17 UTC, NikitaMishin commented on Privalihin/Task03/src/AVLTree.kt
> +        var flag = 0
и какой смысл она несет.

2019-05-03 04:13 UTC, AlekseiPrivalihin commented on Privalihin/Task03/src/AVLTree.kt
> +        var flag = 0
переименовал в subtreeSizeDifference

2019-05-03 04:14 UTC, AlekseiPrivalihin commented on Privalihin/Task03/src/RBTree.kt
> +        // Maybe I should replace it with an enum class
Создал enum class Color и переделал на него. Крайне непонятно, почему Котлин запрещает создание внутренних enum классов. В итоге пришлось сугубо внутреннюю для RB-дерева вещь выносить во внешний класс

2019-05-03 04:14 UTC, AlekseiPrivalihin commented on Privalihin/Task03/src/BinarySearchTree.kt
> +                    curNode.right = createNode(value, key, curNode)
переделал

2019-05-03 04:15 UTC, AlekseiPrivalihin commented on Privalihin/Task03/src/BinarySearchTree.kt
> +    protected open var root: Node? = null
это артефакт более старой версии, убран

2019-05-03 04:16 UTC, AlekseiPrivalihin commented on Privalihin/Task03/src/BinarySearchTree.kt
> +        var left: Node? = null
вынес в конструктор

2019-05-03 04:27 UTC, AlekseiPrivalihin commented on Privalihin/Task03/src/BinarySearchTree.kt
> +    public open inner class Node(_value: T, _key: K, _parent: Node?) {
inner нужен, чтобы узел знал шаблонные параметры дерева. Порядок поменял на "ключ, значение"

2019-05-03 04:31 UTC, AlekseiPrivalihin commented on Privalihin/Task03/src/AVLTree.kt
> +        var flag = 0
принтер (хотя вообще говоря, в задание он не входит) я переделал. Возможно, так будет удобнее читать

2019-05-03 08:20 UTC, NikitaMishin commented on Privalihin/Task03/src/BinarySearchTree.kt
> +    public open inner class Node(_value: T, _key: K, _parent: Node?) {
ок, но сами узлы ведь могут быть параметризованными. Но так тоже пойдет (здесь был основной поинт в том, чтобы узлы не знали деревьях )

2019-05-03 08:23 UTC, NikitaMishin commented on Privalihin/Task03/src/RBTree.kt
> +        // Maybe I should replace it with an enum class
ну можно так, например, тогда

    object Color{
        enum class Color{
            RED,BLACK
        }
    }

2019-05-03 08:23 UTC, NikitaMishin commented on Privalihin/Task03/src/AVLTree.kt
> +        var flag = 0
ок

2019-05-03 08:34 UTC, NikitaMishin requested changes
![Screenshot_2019-05-03_11-34-23](https://user-images.githubusercontent.com/22191229/57126957-7f047a80-6d97-11e9-8867-9f71984d5d94.png)


Что-то не так у вас с авл деревом, надо поправить, у вас св-во не выполняется авл дерева, то что для каждой вершины высота  её двух поддеревьев различается не более чем на 1. Тут как-то это не работает)) Наверное, поэтому такой странный отрицательный sizeDifference (могу посоветовать написать тест isAVlTree, как писал выше) Это поможет быстро отловить баг и намного легче кому-то да и вам проверять

2019-05-04 19:29 UTC, AlekseiPrivalihin commented on Privalihin/Task03/src/RBTree.kt
> +        // Maybe I should replace it with an enum class
Оставлю как есть, пожалуй. Баги в АВЛ и красно-черном деревьях выловил, добавил функции верификации и тесты.

2019-05-06 09:28 UTC, AlekseiPrivalihin commented
Изменил структуру так, чтобы insert() не возвращала вставленную вершину. Таким образом, пользователь не может получать доступ к вершинам дерева и портить их.

2019-05-06 17:48 UTC, EgorkaKulikov commented
Баги, конфликты, нет прогона командных тестов, пока, видимо, не готово

2019-05-07 21:16 UTC, AlekseiPrivalihin commented
конфликты разрешены, известных багов в коде нет, тесты добавляются по мере их создания

2019-05-08 09:14 UTC, AlekseiPrivalihin commented
@NikitaMishin архитектура приведена в конечный вид, добавлены некоторые тесты и отчет об их прохождении

2019-05-16 18:38 UTC, NikitaMishin commented on Privalihin/Task03/Tests/binaryTrees/AVLTreeTest.kt
> +    fun stressTest() {
какая наиболее частая операция в деревьях? Поиск. Стресс тест должен это отоброжать. 
И, например , еще может быть тест, показывающий, что двоичное дерево может сильно проседать. При последовательной вставки элементов - асимптотика поиска - линия.

2019-05-16 18:40 UTC, NikitaMishin commented on Privalihin/Task03/src/binaryTrees/BinarySearchTree.kt
> +    public open inner class Node(internal var key: K, internal var value: V, internal var parent: Node?) {
просто замечание, ключ у нас ведь , по-хорошему , должен быть val, ибо он неизменен (понятно, что это сделано, чтобы было меньше проблем с реализацией алгоритмов, но надо это иметь в виду)

2019-05-16 18:55 UTC, NikitaMishin approved these changes
отдельное спасибо за фукнции, котрые проверяют свойства деревьев,они и вам, наверное, помогли при написании (надеюсь, табличку посомтрел, у нее верстка, наверное слетела)
![Screenshot_2019-05-16_21-53-47](https://user-images.githubusercontent.com/22191229/57879422-1ef4e600-7825-11e9-993f-f08e336f837b.png)
 Ну и стресс тесты все-таки на основную функцинальность деревье делать(а то увидеть, чем обычное дерево поиска хуже рб и авл,  нельзя), теперь все работает корректно (попытался сломать, не получилось)

2019-05-16 20:56 UTC, EgorkaKulikov commented
Стресс-тесты по желанию, если есть интерес и время. Со всех их точно требовать не будем.
@NikitaMishin здесь полный аппув: дерево, тесты, итератор? Просьба в остальных местах оставлять коммент про это, а то задача составная.

2019-05-16 21:07 UTC, NikitaMishin commented
yes, all completed

2019-05-16 22:26 UTC, merged