Task03&Task04_Abzalov
EgorkaKulikov/spbu-se2019-spring pull request #38
Opened 2019-04-25 09:45 UTC by foxyelite

2019-05-03 12:30 UTC, NikitaMishin requested changes
1)Очень понравилось тестовое покрытие, пока ни у кого не видел такого количества тестов. Зачетно)
2) В комментариях некоторые мелкие замечания и вопросы
3) Очень смущает огромное количество кода (это про повторяющиеся  куски кода и одинаковые методы). От копипасты методов хотелось бы избавиться(например, те же итераторы или  методы у узлов).
Наверное, наличие дублирующегося кода и методов - результат архитектуры, но итераторы явно можно и нужно поправить.
А так мне нравится.
Насчет тестов могу посоветовать добавить по функции в тесты для авл и рб дерева , которые бы проверяли, удовлетворяет ли представленное дерево заявленным свойствам. Тогда будет полное тестовое покрытие, на мой взгляд. Это просто как совет

2019-05-03 12:30 UTC, NikitaMishin commented on Task03/src/BinarySearchTree/Tree.kt
> +    var root: Node<K, V>? = null
мне кажется, давать пользователю доступ к руту не очень хорошая затея. Стоит сделать приватным или протектед

2019-05-03 12:30 UTC, NikitaMishin commented on Task03/src/BinarySearchTree/Tree.kt
> +    var root: Node<K, V>? = null
вы, наверное, так сделали, чтобы тестить различные юзкейсы в юнит тестах ?

2019-05-03 12:30 UTC, NikitaMishin commented on Task03/src/BinarySearchTree/Tree.kt
> +    var root: Node<K, V>? = null
могу предложить, чтобы пользователь мог иметь к нему доступ, но не имел возможности модифицировать (хотя тоже так себе решение)

2019-05-03 12:30 UTC, NikitaMishin commented on Task03/src/BinarySearchTree/Tree.kt
> +                if (parent == null) {
суровый каскад вложенности ifoв

2019-05-03 12:30 UTC, NikitaMishin commented on Task03/src/BinarySearchTree/Node.kt
> +        var key: K,
а почему у нас key изменяемый? Не должен ли он у нас быть неизменяемым?

2019-05-03 12:30 UTC, NikitaMishin commented on Task03/src/RedBlackTree/Node.kt
> +        var isBlack: Boolean = false
здесь можно enum

2019-05-03 12:36 UTC, NikitaMishin commented
мб еще  одинообразные тесты как-то тоже смержить, чтобы  тоже не было копипасты

2019-05-03 13:13 UTC, foxyelite commented on Task03/src/BinarySearchTree/Node.kt
> +        var key: K,
В реализации удаления необходимо изменять значения полей `key` и `value`

2019-05-03 13:19 UTC, foxyelite commented on Task03/src/BinarySearchTree/Tree.kt
> +                if (parent == null) {
К сожалению, в реализации деревьев без такого не обойтись

2019-05-03 14:07 UTC, foxyelite commented on Task03/src/BinarySearchTree/Tree.kt
> +    var root: Node<K, V>? = null
Изменены модификаторы доступа: `root` на `internal root`, `class Node` на `internal class Node`.

2019-05-03 14:09 UTC, foxyelite commented
Добавлены тесты для достижения 100% покрытия кода.
Итератор не вынесен из-за особенностей архитектуры.
Тесты не смержены из-за особенностей архитектуры.

2019-05-03 15:07 UTC, NikitaMishin commented on Task03/src/BinarySearchTree/Node.kt
> +        var key: K,
можно обойти это ограничение, но ок, не столь существенно

2019-05-06 17:50 UTC, EgorkaKulikov commented
@NikitaMishin какой тут статус по коду? норм?

2019-05-06 17:51 UTC, EgorkaKulikov commented
По поводу прогона тестов: мне казалось, что все эти тест раннеры умеют делать красивые отчётики с зелёными галочками и красными крестиками, где открываешь и сразу глазами видно, что всё  пройдено.

2019-05-06 17:52 UTC, NikitaMishin commented
yep

> @NikitaMishin какой тут статус по коду? норм?

yep

2019-05-06 17:54 UTC, NikitaMishin approved these changes

2019-05-06 17:55 UTC, NikitaMishin commented
> По поводу прогона тестов: мне казалось, что все эти тест раннеры умеют делать красивые отчётики с зелёными галочками и красными крестиками, где открываешь и сразу глазами видно, что всё пройдено.
Ну если по папке вроде ткнуть, то он все абсолютно прогонит

2019-05-16 21:09 UTC, NikitaMishin commented
тут тоже полный апрув

2019-05-17 14:16 UTC, merged