Task01_Tsirikov
EgorkaKulikov/spbu-se2019-spring pull request #4
Opened 2019-03-12 14:41 UTC by Tsirikov

2019-03-16 20:54 UTC, EgorkaKulikov requested changes

2019-03-16 20:54 UTC, EgorkaKulikov commented on Task01/matrix.kt
> +  var zeroes: Int = if (N*(N - 1)/2 > M) N*(N - 1)/2 - M else 0
Посмотрите внимательно на эту строчку. Как вижу её я:
целое число нулей есть в каком-то странном случае какая-то разность, в противном - ноль.

2019-03-16 20:54 UTC, EgorkaKulikov commented on Task01/main.kt
> +  print("It`s ${res1.contentEquals(res2)} that ")
В интерполированных строках только локальные переменные.

2019-03-16 20:54 UTC, EgorkaKulikov commented on Task01/matrix.kt
> +
В принципе, правила "одно условие - одна строка" или "все условия - одна строка" не исчерпывают все случаи жизни. В данном случае даже не знаю, как лучше. Очень непонятная проверка в строках 57-60.

2019-03-16 20:54 UTC, EgorkaKulikov commented on Task01/algorithms.kt
> +
@iakov,  есть ли какие-то мысли по этому коду? 
С одной стороны, всё прописано скурпулёзно и с глубочайшим погружением в новый язык, снимаю шляпу. Локально всё замечательно. Но при этом глобально не покидает ощущение какой-то монструозности, что-то в стиле "так не пишут". Не первый раз такое замечаю при чтении кода Семёна. У меня что-то субъективное полезло?

2019-03-16 20:54 UTC, EgorkaKulikov commented on Task01/algorithms.kt
> +
@skoret, присоединяйся :)

2019-03-17 21:06 UTC, KutuevVladimir commented on Task01/algorithms.kt
> +fun algFordBellman(matrix: Array<Array<Int>>, start: Int): Array<Int>
Это не алгоритм Форда-Беллмана, здесь реализовано что-то близкое к алгоритму Флойда-Уоршелла.

2019-03-18 04:14 UTC, Tsirikov commented on Task01/matrix.kt
> +  var zeroes: Int = if (N*(N - 1)/2 > M) N*(N - 1)/2 - M else 0
Почему-то казалось, что в контексте создания матрицы смежности переменная "нули" не должна сбивать с толку (0 - отстутствие ребра между вершинами, соответственно счётчик их количества - между сколькими вершинами можно не создавать ребро).
N*(N - 1)/2 - число наддиагональных элементов и максимальное число рёбер для графа с данным количеством вершин. Если оно <= М (числа рёбер, с которым пытаемся создать граф), то у нас между всеми вершинами рёбра есть, > - нужно распределить нули в количестве разности.

2019-03-18 04:16 UTC, Tsirikov commented on Task01/matrix.kt
> +
Почти напрямую связано с предыдущим замечанием. Попытка равномерно распределить значения (а не сначала все рёбра, потом все нули).
В любом случае собираюсь заменить when на if в этом месте, чтобы убрать повторяющиеся проверки.

2019-03-18 19:47 UTC, EgorkaKulikov commented on Task01/algorithms.kt
> +
Ладно, если никто не отметился, то будем считать, что мне мерещится

2019-03-18 19:49 UTC, EgorkaKulikov commented on Task01/algorithms.kt
> +fun algFordBellman(matrix: Array<Array<Int>>, start: Int): Array<Int>
@Tsirikov кажется, Вова прав, я ещё заметил что что-то очень знакомое, и у других я этого не видел...

2019-03-26 16:19 UTC, Tsirikov commented on Task01/algorithms.kt
> +fun algFordBellman(matrix: Array<Array<Int>>, start: Int): Array<Int>
@KutuevVladimir Единственное, чем отличается моя запись Форда-Беллмана от эталонного псевдокода в учебниках - это проход по матрице смежности через два цикла вместо одного по массиву рёбер. Флойд-Уоршел предназначен для поиска кратчайших расстояний от всех до всех и возвращает соответственно матрицу NxN, здесь же ищется только от одной до остальных, на выходе 1xN.  
@EgorkaKulikov  Замечание, что я единственный, кто так сделал, тоже непонятно: сравните с 1, 9, 10, 14, 15 реквестами.

2019-03-26 19:26 UTC, merged