Task02_Afonina
EgorkaKulikov/spbu-se2019-spring pull request #41
Opened 2019-04-27 17:01 UTC by AfoninaOlga

2019-04-29 14:04 UTC, Tiltedprogrammer requested changes
Неплохое ревью, осталось ответить на вопросы и будет аппрув.

2019-04-29 14:04 UTC, Tiltedprogrammer commented on Task02/review.txt
> +                ��������� �� ���� ��� �� ����� Brainfuck � �������������� ���, ��������� "������" �������, ������ ��,
Было бы неплохо написать, откуда интерпретатор берет код и куда выводит результат

2019-04-29 14:04 UTC, Tiltedprogrammer commented on Task02/review.txt
> +        ������ (��������, +[+-]).
> отсутствует обработка бесконечных циклов (например, +[+-]).

Ну это вполне корректное поведение программы (такой язык), питон же, например, не отказывается исполнять программу если там `while true`. Хотя, я вас возможно неправильно понял.

2019-04-29 14:04 UTC, Tiltedprogrammer commented on Task02/review.txt
> +Compiler:
Там в пул реквесте есть также компилятор для `Petooh`, с комментарием о надобности переиспользования кода, было бы интересно услышать, ваши мысли по архитектуре компилятора, чтобы таких ситуаций не возникало.

2019-04-29 14:59 UTC, Tiltedprogrammer commented on Task02/review.txt
> +______________________________________________________________________________________
Еще вы про тесты совсем ничего не написали, а там много чего можно сделать лучше (в принципе и идеологически). Имена функций в тестах обычно содержат слово `Test` В тестах для интерпретатора, все тесты имеют одинаковые первые 3 и последнюю строчки. Их можно вынести в отдельное место с нужной аннотацией.
Ну и вообще наличие кода после `assertEquals` выглядит странным.

2019-05-01 22:29 UTC, EgorkaKulikov commented
@AfoninaOlga ждём ответов на вопросы

2019-05-03 23:02 UTC, Tiltedprogrammer approved these changes
Считаю, что замечания исправлены и надеюсь, что хоть про тесты и не написано, но что  комментарий про них принят к сведению

2019-05-06 17:52 UTC, merged