Task04_Privalikhin
EgorkaKulikov/spbu-se2019-spring pull request #44
Opened 2019-05-02 12:23 UTC by AlekseiPrivalihin

2019-05-02 22:34 UTC, NikitaMishin requested changes
что-то не так с итератором
такой код возвращает лишь единицу

   private val tree = IterableSearchTree<Int, Int>()

    @Test
    fun basicTest() {
        for (i  in 100 downTo  1 step 1 ) {
            tree.insert(i * i, i)
        }


        for(i in tree) {
            println(i)
        }
    }

2019-05-02 22:36 UTC, NikitaMishin commented on Privalihin/Task04/src/IterableSearchTree.kt
> +class IterableSearchTree<T, K: Comparable<K>>: Iterable<T> {
верно понимаю, что  у вас впослдетсвии Iterable будет реализовывать  BinarySearchTree ?

2019-05-02 22:36 UTC, NikitaMishin commented on Privalihin/Task04/src/IterableSearchTree.kt
> +                return null!!
return null!! ? а зачем?

2019-05-03 02:04 UTC, AlekseiPrivalihin commented on Privalihin/Task04/src/IterableSearchTree.kt
> +                return null!!
Ну, при попытке вызвать next() от конца, насколько я понимаю, должна вылетать ошибка. Если не выдавать ошибку, поведение функции становится неопределенным (непонятно, что возвращать). Стандартное поведение при вызове next() от end() - вылет с ошибкой. Можно вставить туда какую-нибудь другую ошибку, но вопрос в том, какую (OutOfRangeException? OutOfBoundsException?)

2019-05-03 02:05 UTC, AlekseiPrivalihin commented on Privalihin/Task04/src/IterableSearchTree.kt
> +class IterableSearchTree<T, K: Comparable<K>>: Iterable<T> {
нет, это две отдельные задачи

2019-05-03 02:35 UTC, AlekseiPrivalihin commented on Privalihin/Task04/src/IterableSearchTree.kt
> +                return null!!
Поменял на бросок IndexOutOfBoundsException(), но все равно выглядит странно. Исправил работу итератора.

2019-05-03 08:04 UTC, NikitaMishin commented on Privalihin/Task04/src/IterableSearchTree.kt
> +                return null!!
так у вас ведь есть функция hasNext для проверки , есть ли следующий элемент

2019-05-03 08:13 UTC, NikitaMishin commented on Privalihin/Task04/src/IterableSearchTree.kt
> +                return null!!
да, теперь более менее сносно принтится, только зеркально, но да ладно)

2019-05-03 08:14 UTC, NikitaMishin approved these changes

2019-05-03 10:07 UTC, merged