Task03&04_Shaposhnikov
EgorkaKulikov/spbu-se2019-spring pull request #49
Opened 2019-05-04 12:29 UTC by Shaposhnikov-Alexey

2019-05-16 19:41 UTC, Tiltedprogrammer requested changes
В целом по коду замечаний нет, замечания про итератор и узлы касаются всех деревьев.

2019-05-16 19:41 UTC, Tiltedprogrammer commented on Shaposhnikov/Task03&04/BSTree/BSTree.kt
> +                val node = current
Вызов ```next()``` у итератора, когда ```hasNext()``` false бросает ```java.util.EmptyStackException ```, а должно по идее что-то такое 
![image](https://user-images.githubusercontent.com/22172264/57879198-865e6600-7824-11e9-97cf-b880e4d0291a.png)

2019-05-16 19:41 UTC, Tiltedprogrammer commented on Shaposhnikov/Task03&04/BSTree/BSTree.kt
> +    var root : BSTNode<K, V>? = null
Вряд ли ```root``` должен быть ```public```

2019-05-16 19:41 UTC, Tiltedprogrammer commented on Shaposhnikov/Task03&04/BSTree/BSTree.kt
> +                val node = current
Ну и соответствующий тест нужен, который проверяет, что итератор бросил нужное исключение

2019-05-16 19:41 UTC, Tiltedprogrammer commented on Shaposhnikov/Task03&04/BSTree/BSTNode.kt
> +    var parent : BSTNode<K, V>? = null
зачем нужен parent? 
![image](https://user-images.githubusercontent.com/22172264/57879597-8b6fe500-7825-11e9-8896-87420da5122e.png)

2019-05-16 19:41 UTC, Tiltedprogrammer commented on Shaposhnikov/Task03&04/BSTree/BSTNode.kt
> +class BSTNode<K : Comparable<K>, V>(
В таком виде можно создать узел, не имея дерева, интуитивно не понято что это означает, все таки узлы существуют только внутри дерева. Скорее всего это должно быть вложенным классом

2019-05-16 19:41 UTC, Tiltedprogrammer commented on Shaposhnikov/Task03&04/BSTree/BSTree.kt
> +    override fun iterator(): Iterator<BSTNode<K, V>> {
Еще у вас в каждом классе итератор написан одинаково, а это дублирование кода. Надо с этим что-то сделать.

2019-05-16 19:41 UTC, Tiltedprogrammer commented on Shaposhnikov/Task03&04/BSTree/BSTree.kt
> +    override fun iterator(): Iterator<BSTNode<K, V>> {
В смысле не написать их по-разному, а вынести куда-нибудь

2019-05-16 19:41 UTC, Tiltedprogrammer commented on Shaposhnikov/Task03&04/RBTree/RBNode.kt
> +    var isRed : Boolean = true
тут наверное лучше enum

2019-05-16 19:41 UTC, Tiltedprogrammer commented on Shaposhnikov/Task03&04/RBTree/RBNode.kt
> +    var isRed : Boolean = true
и опять все паблик и доступно даже без дерева

2019-05-16 19:41 UTC, Tiltedprogrammer commented on Shaposhnikov/Task03&04/BSTree/BST_tests.kt
> +            assertEquals(tree.find(num), Pair(num, num))
перепутан порядок expected и actual

2019-05-16 19:41 UTC, Tiltedprogrammer commented on Shaposhnikov/Task03&04/RBTree/RBNode.kt
> +    var isRed : Boolean = true
Если видимость и нода не в дереве сделаны ради тестов, то могу предложить модификатор internal

2019-05-16 19:42 UTC, Tiltedprogrammer commented on Shaposhnikov/Task03&04/BSTree/BST_tests.kt
> +            assertEquals(tree.find(num), Pair(num, num))
и вроде еще в нескольких тестах, так что поправьте везде

2019-05-16 22:30 UTC, Tiltedprogrammer commented on Shaposhnikov/Task03&04/BSTree/BSTree.kt
> +    override fun iterator(): Iterator<BSTNode<K, V>> {
также итератор возваращает узел, что дает право менять структуру дерева, а это как-то неправильно

2019-05-17 14:19 UTC, EgorkaKulikov commented on Shaposhnikov/Task03&04/BSTree/BSTree.kt
> +    override fun iterator(): Iterator<BSTNode<K, V>> {
да, аналогичную проблему я писал Глебу
этот косяк архитектуры нужно устранить обязательно, потому что итератор в данном случае от вида дерева не зависит

2019-05-17 15:13 UTC, EgorkaKulikov commented on Shaposhnikov/Task03&04/RBTree/RBNode.kt
> +    var isRed : Boolean = true
@Tiltedprogrammer, а как тут с помощь equals это сделать? Я не очень понял, что имелось в виду.

2019-05-17 18:58 UTC, Tiltedprogrammer commented on Shaposhnikov/Task03&04/RBTree/RBNode.kt
> +    var isRed : Boolean = true
Я предположил, что все поля ```public``` для того, чтобы в тестах к ним иметь доступ и что-то проверять для них в assert'e и поэтому предложил, что в таком случае можно определить равенство  узлов и проверять на equals узлы. Хотя решение с вложенным классом и internal модификаторами, видимо, лучший вариант.

2019-05-21 18:03 UTC, EgorkaKulikov requested changes
Написал ещё несколько небольших замечаний от себя

2019-05-21 18:03 UTC, EgorkaKulikov commented on Shaposhnikov/Task03&04/AVLTree/AVLNode.kt
> +        val curRight = this.right ?: return
Очень много лишних явных указаний слова this, на мой взгляд
Если здесь просто написать  val curRight = right ?: return, понимаемость не снизится.

2019-05-21 18:03 UTC, EgorkaKulikov commented on Shaposhnikov/Task03&04/AVLTree/AVLNode.kt
> +        val curLeft = this.left ?: return
А разумно ли здесь делать return? То есть мы наткнулись на что-то непредвиденное, ничего не повернули и молча покинули процедуру. Мне кажется, это exception.

2019-05-21 18:03 UTC, EgorkaKulikov commented on Shaposhnikov/Task03&04/AVLTree/AVLTree.kt
> +        if (current == null) {
Я предлагаю здесь написать root == null, а current ввести ниже, там, где в нём реально возникает необходимость.

2019-05-21 18:03 UTC, EgorkaKulikov commented on Shaposhnikov/Task03&04/AVLTree/AVLTree.kt
> +            key > parent.key -> {
А как тут работает, почему в 30 строке есть !!, а здесь нет?

2019-05-21 18:03 UTC, EgorkaKulikov commented on Shaposhnikov/Task03&04/BSTree/BSTNode.kt
> +    var parent : BSTNode<K, V>? = null
Видимо, оно тут нужно для всех остальных деревьев, но отсутствует пометка абстрактности

2019-05-21 18:03 UTC, EgorkaKulikov commented on Shaposhnikov/Task03&04/BSTree/BST_tests.kt
> +            assertEquals(tree.find(num), Pair(num, num))
ну да, по классике assert(expected, actual), так можно очень сильно запутать себя и остальных

2019-05-21 18:03 UTC, EgorkaKulikov commented on Shaposhnikov/Task03&04/RBTree/RBNode.kt
> +    var isRed : Boolean = true
@Shaposhnikov-Alexey @Tiltedprogrammer вы договорились между собой, как разрешить эту проблему?

2019-05-21 18:03 UTC, EgorkaKulikov commented on Shaposhnikov/Task03&04/RBTree/RBTree.kt
> +        while (current != null) {
Вообще говоря, этот while есть вставка в дерево поиска, так что совсем в идеале можно было бы вызвать здесь код вставки в дерево поиска, чтобы не копипастить его, а потом восстановить красно-чёрные свойства. Ну то есть:
insert {
base.insert
fixup
}

2019-05-23 08:20 UTC, Shaposhnikov-Alexey commented on Shaposhnikov/Task03&04/AVLTree/AVLTree.kt
> +            key > parent.key -> {
Так котлин работает. Видимо, он при первой проверке запоминает, что parent !!, при второй уже не возникает вопросов. По крайней мере, если во второй написать !!, идея скажет, что это излишне

2019-05-23 09:51 UTC, Shaposhnikov-Alexey commented on Shaposhnikov/Task03&04/BSTree/BSTree.kt
> +    override fun iterator(): Iterator<BSTNode<K, V>> {
В таком случае итератор нужно выносить в абстрактный класс дерева. Это, конечно, удобнее, но тогда вся архитектура изменится, придется все немного поменять. Это не сложно, просто задание было реализовать дерево в соответствие с архитектурой команды... Вот такая вот она у нас получилась :с
То же касается вложенности узлов в дерево

2019-05-23 09:52 UTC, Shaposhnikov-Alexey commented on Shaposhnikov/Task03&04/BSTree/BSTNode.kt
> +    var parent : BSTNode<K, V>? = null
Я интуитивно его написал, а не для абстрактного класса. Однако [parent] используется в тестах

2019-05-23 09:54 UTC, Shaposhnikov-Alexey commented on Shaposhnikov/Task03&04/BSTree/BSTree.kt
> +                val node = current
Try {} catch() {} сделал, но не совсем понимаю, в каких конкретных случаях будет выводиться Exception. Если мы пытаемся итерироваться по пустому дереву (не уверен, но вроде нет)? Если мы вручную вызввали функцию next()?

2019-05-23 09:56 UTC, Shaposhnikov-Alexey commented on Shaposhnikov/Task03&04/RBTree/RBTree.kt
> +        while (current != null) {
Не совсем понял, как можно вызвать код из другого дерева. Можно было бы написать абстрактное дерево с fun baseInsert() {}, где все это есть, а затем в каждом дереве override fun insert() {} необходимый делать, но, опять же, у нас архитектура с интерфейсом -_-

2019-05-23 09:58 UTC, Shaposhnikov-Alexey commented
Недочеты по большей части исправил. Что касается архитектуры (i.e. вынесения итератора), то не трогал (у Вадима с такой архитектурой принято, например). Если все же придется изменить, то ок, поменяю

2019-05-23 12:02 UTC, Tiltedprogrammer commented on Shaposhnikov/Task03&04/BSTree/BSTree.kt
> +                val node = current
Исключение будет, если явно у дерева взять ```iterator```  через соответствующий метод, взять у него ```n``` раз ```next()``` до того момента, когда ```hasNext()``` станет false (т.е. когда перебрали всё) и еще раз вызвать next(). В вашем случае это приводило к pop'у из пустого стека и к соответствующему исключению.

2019-05-23 20:58 UTC, EgorkaKulikov commented
Аргумент про Вадима не очень хороший, но ошибки архитектуры - часть процесса, главное, чтобы они были осознаны на будущее

2019-05-23 20:58 UTC, merged