Task03&Task04
EgorkaKulikov/spbu-se2019-spring pull request #50
Opened 2019-05-04 14:41 UTC by Glebuska

2019-05-07 21:56 UTC, EgorkaKulikov requested changes

2019-05-07 21:56 UTC, EgorkaKulikov commented on AVLTree/AVLNode.kt
> +    var parent:AVLNode<K, V>? = null) {
На мой взгляд, при чтении совершенно не видно, что parent ещё часть конструктора, а left уже нет. Явно нужно отделять пустой строкой или как-то ещё.

2019-05-07 21:56 UTC, EgorkaKulikov commented on AVLTree/AVLNode.kt
> +    fun getHeight(node: AVLNode<K, V>?) = node?.height ?: 0
0 - высота листовой вершины
и 0 в текущей реализации высота null'а
Как отличить вычисление высоты листа и некорректный запрос на вычисление высоты чего-то, чего нет? Сейчас никак.
А если, ?: -1 сделать, то уже можно будет.

2019-05-07 21:56 UTC, EgorkaKulikov commented on AVLTree/AVLNode.kt
> +        val rightChild = this.right ?: throw Exception("Null node")
Опять забываешь, что потом тестировщики пришлют тебе вот такой эксепшен из логов и попросят быстренько починить. Не пожалеешь ли ты, что не написал "Right child for node ... does not exist"?

2019-05-07 21:56 UTC, EgorkaKulikov commented on AVLTree/AVLNode.kt
> +        this.height = max(getHeight(this.left), getHeight(this.right)) + 1
Здесь и много где выше слово this избыточно. Явно его прописывать может иметь смысл, например, в строках 57-59 для определённости, когда рядом фигурируют this.left и leftChild.left. Но в строках 70-77 оно кажется мне лишним.

2019-05-07 21:56 UTC, EgorkaKulikov commented on AVLTree/AVLTree.kt
> +    private fun prefind(key: K, AVLNode: AVLNode<K, V>? = root): AVLNode<K, V>? = when {
Часто такое называют findInternal. Но вообще назначение метода я не вполне понял. Почему бы просто не перенести это в find, разбив первый случай на два подслучая, возвращая из них null и пару соответственно?

2019-05-07 21:56 UTC, EgorkaKulikov commented on AVLTree/AVLTree.kt
> +        while (cur != null) {
А вот это можно вынести в некий общий метод, кажется, одинаковый для всех деревьев.

2019-05-07 21:56 UTC, EgorkaKulikov commented on AVLTree/AVLTree.kt
> +            override fun hasNext(): Boolean {
Ой, а не слишком ли тяжеловесна такая реализация? Ведь hasNext по сути вызывается всегда перед тем, как next брать, разве нет? Мне кажется, он должен быть максимально быстрым. 
Это достаточно фундаментальный вопрос к данному PR, можно тегнуть ребят или погуглить, не заблуждаюсь ли я.

2019-05-07 21:56 UTC, EgorkaKulikov commented on README.md
> -# Программная инженерия 2018-2020
Ой! А зачем же это удалять? ;(
Я ещё удивился, откуда удаления в PR по новой задаче. Полезно всегда проглядывать дифы на предмет явной лажи при создании пулреквеста.

2019-05-07 21:56 UTC, EgorkaKulikov commented on Test Results - TestBank.xml
> +        <test duration="1" locationUrl="java:test://TestBank/testSearchCase2" name="Search case 2" metainfo="" status="passed"/>
Именование тестов, завтра попробую не забыть поговорить про это на паре.

2019-05-07 21:56 UTC, EgorkaKulikov commented on binaryTree/BSTNode.kt
> +) {
Вот! Здесь, в отличие от АВЛ, выглядит гораздо читаемее.

2019-05-07 21:56 UTC, EgorkaKulikov commented on binaryTree/BSTNode.kt
> +
К вопросу о пользе базовой ноды: можно было бы разработать общий equals и дальше дополнить его по необходимости. Например, в случае АВЛ было бы base.Equals && height = other.Height. А остальное не пришлось бы копировать, а потенциально ещё и править в трёх местах в случае, если бы ты изначально попытался включить сравнение пэрентов сюда.

2019-05-07 21:56 UTC, EgorkaKulikov commented on binaryTree/BSTNode.kt
> +        result = 31 * result + (parent?.hashCode() ?: 0)
Ой! Тут очень странно (мб и выше тоже, но не заметил). Почему parent участвует в хэш коде, если оно не участвует в equals? Не сломает ли это условие, что если a equals b, то hashCode(a) = hashCode(b) ?
@NikitaMishin подскажи, пожалуйста.

2019-05-07 21:56 UTC, EgorkaKulikov commented on binaryTree/BinaryTree.kt
> +}
Строки 85-95 адски много лишних пробелов. И много где их много.

2019-05-07 21:56 UTC, EgorkaKulikov commented on binaryTree/BinaryTree.kt
> +    override fun iterator() : Iterator<BSTNode<K, V>> =
Код очень отдаёт копипастом. Но здесь более фундаментальный вопрос: а зачем нам для наших деревьев разные итераторы, если они отличаются только методами балансировки, но не структурой?
Мне понравилась идея у кого-то не помню кого выделить промежуточный интерфейс IterableTree и имплементировать во всех наших деревьях его. А в этот интерфейс поместить необходимые методы.

2019-05-07 21:56 UTC, EgorkaKulikov commented on redBlackTree/RBNode.kt
> +    fun grandparent(): RBNode<K, V>? = this.parent?.parent
А почему это дедушка и дядя это методы, а не свойства? Выглядит странно.

2019-05-07 21:56 UTC, EgorkaKulikov commented on redBlackTree/RBNode.kt
> +        //this == parent
Не понял смысла комментария. Эффект скорее отрицательный от него.

2019-05-07 21:56 UTC, EgorkaKulikov commented on redBlackTree/RBNode.kt
> +        this.swapColors(rightChild)
Опять странный this. Вот если super, тогда нужно писать, а тут то зачем?

2019-05-07 21:56 UTC, EgorkaKulikov commented on redBlackTree/RedBlackTree.kt
> +    private fun treeBalance(RBNode: RBNode<K, V>) {
Лучше всё-таки balanceTree. Функция есть действие, действие балансировки дерева.

2019-05-07 21:56 UTC, EgorkaKulikov commented on redBlackTree/RedBlackTree.kt
> +            treeBalance(parent.left ?: throw Exception("Incorrect BSTNode's construction"))
Мне кажется, так делать не стоит. Хотя бы потому, что не вполне понятно, где оно пробросится: до вызова подпрограммы, после, что мы увидим в стеке вызовов и не появятся ли какие-нибудь нежелательные спецэффекты.
Ну и читаемости не способствует.

2019-05-07 21:56 UTC, EgorkaKulikov commented on test/AVLTreeTest.kt
> +        for (x in a) {
А почему вдруг в тестах полезли какие-то странные имена переменных вроде x и a? Почему не foreach (node in nodesToInsert)?

2019-05-07 21:56 UTC, EgorkaKulikov commented on test/AVLTreeTest.kt
> +    //New test for AVLTree
Тоже так себе комментарий.

2019-05-07 21:56 UTC, EgorkaKulikov commented on test/AVLTreeTest.kt
> +
Совсем нигде не видно тестов на исключительные ситуации.

2019-05-16 22:56 UTC, NikitaMishin commented on binaryTree/BSTNode.kt
> +        result = 31 * result + (parent?.hashCode() ?: 0)
да, можно использовать не все поля, но в обоих методах **должны** участвовать те же самые поля (если в equals  есть parent, то должен быть в hashCode и наоборот)

2019-05-17 06:24 UTC, NikitaMishin commented on binaryTree/BSTNode.kt
> +        result = 31 * result + (parent?.hashCode() ?: 0)
Банальный пример 
class Male {
string name;
bool have_wife;
} И у нас в hashcode будет только бул--- что-то плохое явно произойдет, а в equals string))))

2019-05-19 10:15 UTC, Glebuska commented on AVLTree/AVLTree.kt
> +    private fun prefind(key: K, AVLNode: AVLNode<K, V>? = root): AVLNode<K, V>? = when {
Назначение этого метода - рекурсивный проход по вершинам дерева. Если не использовать вспомогательный метод, то рекурсия отпадает, а, на мой взгляд, она тут как нельзя кстати

2019-05-19 10:51 UTC, Glebuska commented on AVLTree/AVLTree.kt
> +    private fun prefind(key: K, AVLNode: AVLNode<K, V>? = root): AVLNode<K, V>? = when {
Решил все-таки исправить. Лучше же не использовать вспомогательные функции, которые используются всего один раз, верно?

2019-05-19 12:49 UTC, Glebuska commented on binaryTree/BSTNode.kt
> +        result = 31 * result + (parent?.hashCode() ?: 0)
Изначально в equals был parent, но потом его убрал из-за зацикливания, а в hasCode убрать parent забыл.

2019-05-20 12:48 UTC, Glebuska commented on redBlackTree/RBNode.kt
> +        //this == parent
Было комментарий больше для себя, чтобы знать относительного чего идет поворот

2019-05-20 12:51 UTC, Glebuska commented on test/AVLTreeTest.kt
> +        for (x in a) {
Насчет nodeToInsert - согласен. Но если переименовать переменную x, то получается что-то типа Tree.insert(node, node), что может запутать еще сильнее

2019-05-20 12:58 UTC, Glebuska commented on redBlackTree/RBNode.kt
> +    fun grandparent(): RBNode<K, V>? = this.parent?.parent
Захотел, чтобы свойства у всех вершин были одинаковые. А новые свойства, отличные от других, показывали явную суть дерева(как цвет или вес)

2019-05-21 17:44 UTC, EgorkaKulikov commented on AVLTree/AVLTree.kt
> +    private fun prefind(key: K, AVLNode: AVLNode<K, V>? = root): AVLNode<K, V>? = when {
В принципе, можно и использовать, если они действительно вспомогательные, но не когда они выносят 3 строчки из метода на 7 строчек

2019-05-21 18:04 UTC, EgorkaKulikov commented
Дай мне явно знать, пожалуйста, когда пора смотреть заново

2019-05-22 19:24 UTC, closed without merging