Task04_Kanashin
EgorkaKulikov/spbu-se2019-spring pull request #51
Opened 2019-05-04 15:47 UTC by KanashinDmitry

Added solution for Task04

2019-05-06 18:48 UTC, EgorkaKulikov requested changes

2019-05-06 18:48 UTC, EgorkaKulikov commented on Task04/IterableSearchTree.kt
> +
Дырка странная

2019-05-06 18:48 UTC, EgorkaKulikov commented on Task04/IterableSearchTree.kt
> +        if (this.root == null) {
А почему не сработает, если слово this здесь не писать везде?

2019-05-06 18:48 UTC, EgorkaKulikov commented on Task04/IterableSearchTree.kt
> +        while (currNode!!.key != key) {
в данном месте !! выглядит весьма опасно

2019-05-06 18:48 UTC, EgorkaKulikov commented on Task04/IterableSearchTree.kt
> +class IterableSearchTree<K: Comparable<K>, T>: Iterable<T> {
В принципе, очень интересная идея сделать промежуточный интерфейс. И дальше тогда наследовать деревья уже от него.

2019-05-06 18:48 UTC, EgorkaKulikov commented on Task04/IterableSearchTree.kt
> +                    if (nextNode.parent?.right == nextNode){
А здесь разве не left ?

2019-05-07 16:49 UTC, KanashinDmitry commented
Внесены требуемые изменения

2019-05-07 19:13 UTC, EgorkaKulikov commented
Хорошо, только вопрос: если я глазами правильно понял, что надо right заменить на left, то как же вы отлаживали свой итератор? Неужели ни один тестовый случай этого не отловил?

2019-05-07 19:13 UTC, EgorkaKulikov approved these changes

2019-05-07 19:13 UTC, merged