Task04_Tsirikov
EgorkaKulikov/spbu-se2019-spring pull request #53
Opened 2019-05-05 15:24 UTC by Tsirikov

2019-05-06 18:34 UTC, EgorkaKulikov requested changes

2019-05-06 18:34 UTC, EgorkaKulikov commented on Task04/main.kt
> +      get()
Практически никогда не следует делать свойства со столь объёмной логикой геттеров/сеттеров, если в этом нет реальной необходимости. В данном случае вас оправдывает только то, что оно приватное. Иначе вообще беда: кто-нибудь вызовет, ничего не подозревая, и производительность резко просядет.

2019-05-06 18:34 UTC, EgorkaKulikov commented on Task04/main.kt
> +    private var next: Node<K, V>? = null
Вообще говоря, вычисление next внутри hasNext выглядит как очень странное с точки зрения структуры приложения действие. Метод, который проверяет наличие объекта, вряд ли должен заниматься его построением.

2019-05-06 18:34 UTC, EgorkaKulikov commented on Task04/main.kt
> +        else if (next?.right != null)
Здесь явно просматриваются целые логические блоки вроде нахождения самой левой вершины в правом поддереве. Давайте вынесем их в методы и проведём разумную декомпозицию. Метод на 50 строчек из сплошных условий выглядит почти не читаемым.

2019-05-09 09:35 UTC, Tsirikov commented on Task04/main.kt
> +    private var next: Node<K, V>? = null
Чтобы определить следующий экземпляр, его нужно найти, используя те же действия, что и для проверки на его существование. Для итератора, который выдит эти методы как if ( hasNext() ) { next() }, ход работы никак не меняется.

2019-05-11 21:07 UTC, merged