Task03&04_Logunov
EgorkaKulikov/spbu-se2019-spring pull request #56
Opened 2019-05-06 19:04 UTC by DanielELog

Task03&04 solution added, including Trees, Nodes and some Tests

2019-05-16 21:53 UTC, NikitaMishin requested changes
классно, что нет дублирующегося код, это классно!
Мне понравлиось
Есть пара замечаний, которыые написаны выше.
1)По итератору все ок (небольшое замечание по поводу того, что возвращает итератор)
2)По деревья норм, но нужно поправить проблему с hashCode точно. И просто замечение, что  для пользователя может быть неочевидно, что вставка в дерево осуществляется через квадратные скобки--- можно предоставить и альетрнативный способ добавления просто через метод.
3) Тестов показалось, что маловато. Нет проверки на то, что деревья сохраняют заявленные свойства, ну и простые тесты на поиск и вставку элементов

2019-05-16 21:53 UTC, NikitaMishin commented on Task03/Node.kt
> +enum class Side {
для чего нужен ?

2019-05-16 21:53 UTC, NikitaMishin commented on Task03/AVLTree.kt
> +    override fun equals(other: Any?): Boolean {
если идет переопределение equals, то также необходимо делать оверрайд hashcode, вот хорошее чтиво с пояснением https://stackoverflow.com/questions/14608683/java-what-happens-if-hashcode-is-not-overriden

2019-05-16 21:53 UTC, NikitaMishin commented on Task03/Node.kt
> +        return super.getInfo() + ": ${if (color == Color.Black) "black" else "Red"}"
можно подсветку делать в терминале просто, будет нагляднее, имхо

2019-05-16 21:53 UTC, NikitaMishin commented on Task03/Tree.kt
> +    var root: NodeType? = null
нехорошо, я могу получить доступ к root, у него взять детей и там немного пошаманить в дереве, что оно упадет(
Модификатор должен решить проблему, либо на гет давать копию, например, без ссылок на сыновей

2019-05-16 21:53 UTC, NikitaMishin commented on Task03/Tree.kt
> +    val keys: Array<out Any>?
приятно, а почему не сделать также для для values?

2019-05-16 21:53 UTC, NikitaMishin commented on Task03/BinarySearchTree.kt
> +    override fun equals(other: Any?): Boolean {
аналогично и в других местах

2019-05-16 21:53 UTC, NikitaMishin commented on Task03/Node.kt
> +    var left: NodeType? = null
ктсати, та же проблема, что и с рутом. Я через итератор получаю узел, который могу модифицировать.
в частности, узлы поменять)

2019-05-16 21:53 UTC, NikitaMishin commented on Task03/Tree.kt
> +abstract class Tree<K: Comparable<K>, V, NodeType: Node<K, V, NodeType>>: Iterable<NodeType> {
мы точно хотим отдавать пользователю узел?Он так может много чего попортить

2019-05-19 14:18 UTC, DanielELog commented on Task03/AVLTree.kt
> +    override fun equals(other: Any?): Boolean {
equals был сделан для более удобного тестирования. Не думаю, что будет рационально придумывать алгоритмы хэширования нод и отдельных деревьев

2019-05-19 14:19 UTC, DanielELog commented on Task03/Node.kt
> +        return super.getInfo() + ": ${if (color == Color.Black) "black" else "Red"}"
не всегда вывод может идти в терминал

2019-05-19 14:25 UTC, DanielELog commented
Исправил/добавил некоторые моменты в соответствии с замечаниями.

Тесты, как я понял, идут на всю группу, и я решил не копировать то, что было написано до меня.
@NikitaMishin, жду комментариев

2019-05-21 18:13 UTC, EgorkaKulikov requested changes
Я посмотрел, по коду есть два актуальных вопроса: про getHashCode и про опасность грохнуть дерево через итератор. Плюс не хватает файла с прогоном общекомандных тестов.

2019-05-21 18:13 UTC, EgorkaKulikov commented on Task03/AVLTree.kt
> +    override fun equals(other: Any?): Boolean {
Нет, здесь речь не идёт про придумывание алгоритмов хеширования, можно взять стандартный предлагаемый идеей, например. Просто есть некоторые инварианты на поведение методов equals и gethashcode, которые можно нарушить, переопределив лишь один из двух, что приведёт в неожиданному поведению программы в дальнейшем.

2019-05-21 18:13 UTC, EgorkaKulikov commented on Task03/Tree.kt
> +    var root: NodeType? = null
звучит немного жёстко, но решение разумное в принципе, да
или можно ещё private set наверное использовать

2019-05-22 11:18 UTC, DanielELog commented
Добавил hashCode с equals
Добавил результаты прогонки всех тестов
Не понимаю только, что не так с итератором - все сеттеры для вершины объявлены как internal, откуда они становятся неизменяемыми вне данного проекта

@EgorkaKulikov, жду последующих комментариев

2019-05-22 20:53 UTC, EgorkaKulikov commented on Task03/AVLTree.kt
> +        return root.hashCode()
И тогда у любой пары вершин, вне зависимости от их одинаковости с точки зрения equals, будет одинаковый хэшкод? А зачем так делать? Почему бы не использовать реализацию, которую предлагает IntellijIdea?

2019-05-22 21:32 UTC, DanielELog commented on Task03/AVLTree.kt
> +        return root.hashCode()
IntellijIdea предложила мне возврат значения height как hashCode для вершины AVLNode.
Мне кажется, данный вариант выглядит более перспективно

2019-05-22 22:35 UTC, EgorkaKulikov commented on Task03/AVLTree.kt
> +        return root.hashCode()
Для меня немного странно всё это, но давайте будем тут исходить из принципа "проходит тесты - значит работает".

2019-05-22 22:35 UTC, merged