Task01_Pogozhelskaya
EgorkaKulikov/spbu-se2019-spring pull request #6
Opened 2019-03-13 09:11 UTC by Pogozhelskaya

2019-03-16 21:03 UTC, EgorkaKulikov requested changes
Большая просьба не повторять в коде ошибки других, обсуждавшиеся на парах

2019-03-16 21:03 UTC, EgorkaKulikov commented on Task01/main.kt
> +fun build(N: Int, M: Int) : Array<IntArray> {
Следует посмотреть рекомендации по разбавлению кода пустыми строками. Тут явная простыня.

2019-03-16 21:03 UTC, EgorkaKulikov commented on Task01/main.kt
> +fun build(N: Int, M: Int) : Array<IntArray> {
N, M как параметры функции - зло. И имя build тоже

2019-03-16 21:03 UTC, EgorkaKulikov commented on Task01/main.kt
> +        var end = (1..N).random()
Обсуждали на паре разные способы генерации end > begin

2019-03-16 21:03 UTC, EgorkaKulikov commented on Task01/main.kt
> +    for(i in 0..(N - 1)) {
until

2019-03-16 21:03 UTC, EgorkaKulikov commented on Task01/main.kt
> +    var minEdge = 101
minEdgeWeight? 
101 = 100 + 1? На паре снова говорили, почему магические константы - зло

2019-03-16 21:03 UTC, EgorkaKulikov commented on Task01/main.kt
> +            if (!used[j] && (v == -1 || distances[j] < distances[v])) {
Уверены ли вы, что стороннему читателю понятно, почему v должно быть равно -1?

2019-03-16 21:03 UTC, EgorkaKulikov commented on Task01/main.kt
> +    } else {
else точно с новой строки
всё экономим?

2019-03-17 16:53 UTC, Pogozhelskaya commented on Task01/main.kt
> +    } else {
https://kotlinlang.org/docs/reference/coding-conventions.html#formatting-control-flow-statements

2019-03-17 20:42 UTC, EgorkaKulikov commented on Task01/main.kt
> +    } else {
Спасибо, увидел. Странно, конечно, первый раз вижу

2019-03-18 19:53 UTC, EgorkaKulikov approved these changes

2019-03-26 19:27 UTC, merged