Task03&Task04_Pogozhelskaya
EgorkaKulikov/spbu-se2019-spring pull request #63
Opened 2019-05-09 11:31 UTC by Pogozhelskaya

2019-05-16 19:50 UTC, NikitaMishin requested changes
по 4 задачки seems ok, есть замечания по дубляжу кода
по 3 задачки seems нужны правки, на мой взгляд. 
Общее впечатление: довольно приятно и чисто написано, дублирование кода напрягает.
Кстати, как xml смотреть в нормальном виде? Мне пришлось генерировать html, чтобы посмотреть .
Радует хорошее тестовое покрытие

2019-05-16 19:50 UTC, NikitaMishin commented on Task03&Task04/src/AVLTree/AVLTreeNode.kt
> +    override fun equals(other: Any?): Boolean {
если  идет переопределение equals, то также необходимо делать оверрайд hashcode, вот хорошее чтиво с пояснением https://stackoverflow.com/questions/14608683/java-what-happens-if-hashcode-is-not-overriden

2019-05-16 19:50 UTC, NikitaMishin commented on Task03&Task04/src/AVLTree/AVLTreeNode.kt
> +class AVLTreeNode<Key: Comparable<Key>, Data>(var key: Key, var data: Data, var parent: AVLTreeNode<Key, Data>? = null){
почему key является var?

2019-05-16 19:50 UTC, NikitaMishin commented on Task03&Task04/src/BinarySearchTree/BinarySearchTree.kt
> +package BinarySearchTree
https://stackoverflow.com/questions/12534302/why-should-java-package-name-be-lowercase
насчет наименования пэкэджей

2019-05-16 19:50 UTC, NikitaMishin commented on Task03&Task04/src/AVLTree/AVLTree.kt
> +    var root: AVLTreeNode<Key, Data>? = null
а мы действительно хотим давать доступ пользователю к руту? Нужен модификатор доступа какой-то или же что-т иное

2019-05-16 19:50 UTC, NikitaMishin commented on Task03&Task04/src/BinarySearchTree/BinarySearchTree.kt
> +            if (currentNode.key == key) {
зачем лишний их? можно ведь в when перенести проверку. Будет чище

2019-05-16 19:50 UTC, NikitaMishin commented on Task03&Task04/src/BinarySearchTree/BinarySearchTree.kt
> +            if (currentNode.key > newNode.key) {
а визуально не лучше будет смотреться , если будет when ? мы как раз по всем возможным случаям проходим

2019-05-16 19:50 UTC, NikitaMishin commented on Task03&Task04/src/BinarySearchTree/BinarySearchTree.kt
> +        return
немного не понял, получается, если у нас curNode ==null (дошли до листа) то мы не вставим в дерево узел?

2019-05-16 19:50 UTC, NikitaMishin commented on Task03&Task04/tests/RedBlackTree/RedBlackTreeNode.kt
> +
а есть возможность одинаковые тесты вынести в отдельый класс во избежания дублирования кода?

2019-05-16 19:50 UTC, NikitaMishin commented on Task03&Task04/src/AVLTree/AVLTree.kt
> +    override fun iterator(): Iterator<Pair<Key, Data>> {
аналогично с тестами, есть возможность не дублировать код итераторов? Мне кажется, эт не так сложно сделать

2019-05-16 22:34 UTC, EgorkaKulikov commented
Ещё тут конфликты адские

2019-05-20 15:54 UTC, Pogozhelskaya commented on Task03&Task04/src/BinarySearchTree/BinarySearchTree.kt
> +        return
Я одновременно со спуском по дереву внутри цикла while пытаюсь вставить узел в дерево

2019-05-20 15:54 UTC, Pogozhelskaya commented on Task03&Task04/src/AVLTree/AVLTree.kt
> +    override fun iterator(): Iterator<Pair<Key, Data>> {
В силу особенностей архитектуры такой возможности нет

2019-05-21 18:57 UTC, EgorkaKulikov commented on Task03&Task04/src/AVLTree/AVLTree.kt
> +    override fun iterator(): Iterator<Pair<Key, Data>> {
не ну всё-таки архитектура, которая требует дублировать код итераторов - это как-то совсем неправильно; с аналогичной проблемой сталкивались другие люди из вашей команды, насколько я понимаю, что-то в этом вопросе удалось придумать

2019-05-21 18:57 UTC, EgorkaKulikov commented on Task03&Task04/src/AVLTree/AVLTree.kt
> +    override fun iterator(): Iterator<Pair<Key, Data>> {
других замечаний по пулреквесту нет

2019-05-21 19:01 UTC, foxyelite commented on Task03&Task04/src/AVLTree/AVLTree.kt
> +    override fun iterator(): Iterator<Pair<Key, Data>> {
Да, мы придумали - оставить всё как есть. Так как иное решение влечет за собой ухудшение и так не самой лучшей архитектуры.

2019-05-21 21:14 UTC, EgorkaKulikov commented on Task03&Task04/src/AVLTree/AVLTree.kt
> +    override fun iterator(): Iterator<Pair<Key, Data>> {
@iakov каково Ваше отношение к корректности, а также содержательности в контексте дискуссии последнего комментария?

2019-05-21 21:16 UTC, EgorkaKulikov commented on Task03&Task04/src/AVLTree/AVLTree.kt
> +    override fun iterator(): Iterator<Pair<Key, Data>> {
Если решили оставить как есть, жду обоснования. От автора кода. Насколько мне известно, у других представителей вашей команды получилось в той или иной степени избавиться от этой архитектурной проблемы.

2019-05-22 05:36 UTC, Pogozhelskaya commented on Task03&Task04/src/AVLTree/AVLTree.kt
> +    override fun iterator(): Iterator<Pair<Key, Data>> {
Обоснование:
В нашей архитектуре итератор - это внутренняя сущность, непосредственно связанная как с деревом, так и с его вершинами. Поэтому вынесение итератора несет за собой неизбежное изменение зафиксированной архитектуры. Лично я не вижу способа избавиться от дубляжа кода без "боли".

Просмотрев код других ребят из команды, я увидела решение этой проблемы у одного из ее представителей, но оно было достигнуто путем изменения архитектуры. Хотя, козалось бы, архитектура - это уже нечто утвержденное и неизменяемое.

2019-05-22 20:55 UTC, EgorkaKulikov commented on Task03&Task04/src/AVLTree/AVLTree.kt
> +    override fun iterator(): Iterator<Pair<Key, Data>> {
Окей, интересный взгляд на ситуацию, открывающий большие горизонты для метафизических дискуссий на занятиях.

2019-05-22 20:55 UTC, merged