Task03_Kanashin
EgorkaKulikov/spbu-se2019-spring pull request #66
Opened 2019-05-09 16:41 UTC by KanashinDmitry

Added Task03 solution

2019-05-16 21:38 UTC, Tiltedprogrammer requested changes
В целом хорошо, но есть там пара вопросов и замечаний. У вас в тестах кое-где перепутаны местами параметры у ассертов, и в коде где-то есть пробелы перед, например, ```{```, а где-то нет.

2019-05-16 21:38 UTC, Tiltedprogrammer commented on Task03/AVLTree.kt
> +        var insertedNode = node as AVLNode
Такое количество кастов говорит о том, что с архитектурой что-то не так

2019-05-16 21:38 UTC, Tiltedprogrammer commented on Task03/AVLTreeTests.kt
> +            assertEquals(tree.find(i), i * i)
```assertEquals(expected, actual)``` перепутаны местами

2019-05-16 21:38 UTC, Tiltedprogrammer commented on Task03/BinarySearchTree.kt
> +    fun insert(key: K, value: T) {
В чем профит использования innerInsert?

2019-05-16 21:38 UTC, Tiltedprogrammer commented on Task03/BinaryTreeBalanced.kt
> +        internal fun getUncle(): Node? {
В kotlin обычно не пишут такие методы getName, а просто в соответсвующих полях определяют get() как нужную функцию, но это не замечание, потому что не знаю, имеет ли это какое-то значение

2019-05-16 21:38 UTC, Tiltedprogrammer commented on Task03/BinarySearchTreeTests.kt
> +    fun stressTest() {
что-то у вас стресс тест какой-то не стресс. На мой взгляд он должен проверять отнсительную скорость вставки/поиска у деревьев. Но вы можете меня переубедить. И 1000 довольно мало для стресс теста

2019-05-16 21:39 UTC, Tiltedprogrammer commented
Также можете предложить исправление ситуации с таким количеством кастов.

2019-05-18 10:22 UTC, KanashinDmitry commented on Task03/BinarySearchTree.kt
> +    fun insert(key: K, value: T) {
innerInsert возвращает Node, так мы можем эту Node балансировать, не переписывая вставку. Так же это удобно в некоторых тестах

2019-05-21 18:47 UTC, KanashinDmitry commented on Task03/BinarySearchTreeTests.kt
> +    fun stressTest() {
Изменил на 100 000. Этот тест подразумевался скорее на рандомную вставку и проверку в нем свойств.

2019-05-21 19:56 UTC, KanashinDmitry commented on Task03/AVLTreeTests.kt
> +            assertEquals(tree.find(i), i * i)
Поменял

2019-05-21 20:15 UTC, KanashinDmitry commented
Добавил изменения по замечаниям

2019-05-21 20:57 UTC, EgorkaKulikov commented on Task03/BinaryTreeBalanced.kt
> +        internal fun getUncle(): Node? {
Да, мне кажется, люди массово боятся пользоваться геттерами и сеттерами, почему - не знаю.

2019-05-21 21:03 UTC, EgorkaKulikov requested changes
Подкинул ещё немного вопросов, один фундаментальный

2019-05-21 21:03 UTC, EgorkaKulikov commented on Task03/BinaryTreeBalanced.kt
> +                if (parentOfCurrNode.left == this) {
Может быть, я в ночи туплю, но вот здесь мы вроде как сравнивает две вершины. Но как мы их сравниваем? Разве мы где-то переопределяли equals и getHashCode ?

2019-05-21 21:03 UTC, EgorkaKulikov commented on Task03/BinarySearchTree.kt
> +        } else {
Думаю, можно просто else true без лишних скобок

2019-05-21 21:03 UTC, EgorkaKulikov commented on Task03/BinarySearchTree.kt
> +            root!!.parent == null && root!!.verifyParents()
Вообще, немного смущает использование оператора !! в методах, который проверяет корректность. Кажется, что такой метод падать особенно не должен.

2019-05-21 21:03 UTC, EgorkaKulikov commented on Task03/BinarySearchTree.kt
> +    var size = 0
Имя плохое

2019-05-21 21:52 UTC, KanashinDmitry commented on Task03/BinaryTreeBalanced.kt
> +                if (parentOfCurrNode.left == this) {
Нет, не переопределяли. Здесь он работает как ===, т.е. сравнивает по ссылкам

2019-05-21 22:16 UTC, KanashinDmitry commented on Task03/BinarySearchTree.kt
> +            root!!.parent == null && root!!.verifyParents()
Изменил на ?:

2019-05-22 21:00 UTC, EgorkaKulikov commented on Task03/BinaryTreeBalanced.kt
> +                if (parentOfCurrNode.left == this) {
Окей, спасибо, нюансы Котлина

2019-05-22 21:00 UTC, merged