trees and iterator
EgorkaKulikov/spbu-se2019-spring pull request #67
Opened 2019-05-09 18:14 UTC by nikitavlaev

2019-05-16 23:14 UTC, Tiltedprogrammer requested changes
По коду в целом хорошо.

2019-05-16 23:14 UTC, Tiltedprogrammer commented on Task03&Task04/main/AVLTree.kt
> +    override fun set(key: K, value: V) {
Вы переопределили оператор, но вместе с этим убрали insert, а это как-то неинтуитивно. Все таки переопределение оно как бы бонусное, а не единственный возможный способ что-то сделать.

2019-05-16 23:14 UTC, Tiltedprogrammer commented on Task03&Task04/main/AVLTree.kt
> +        fun leftleftCase(node: AVLNode<K, V>) {
```leftLeftCase ``` потому что так как есть не читается

2019-05-16 23:14 UTC, Tiltedprogrammer commented on Task03&Task04/main/AVLTree.kt
> +        val leftHeight = node.left?.height ?: 0
тут видимо надо пустые строки, потому что как-то кучно

2019-05-16 23:14 UTC, Tiltedprogrammer commented on Task03&Task04/main/AVLTree.kt
> +            if (leftleftHeight - leftrightHeight == 1) { //left left case
тоже кажется, что ``` if ``` надо через строку

2019-05-16 23:14 UTC, Tiltedprogrammer commented on Task03&Task04/main/AVLTree.kt
> +    override fun equals(other: Any?): Boolean {
а где ```hashCode``` ?

2019-05-16 23:14 UTC, Tiltedprogrammer commented on Task03&Task04/main/NodeRotator.kt
> +internal class NodeRotator<K : Comparable<K>, V, NodeType : Node<K, V, NodeType>> {
по архитектуре те же замечания https://github.com/EgorkaKulikov/spbu-se2019-spring/pull/33

2019-05-16 23:14 UTC, Tiltedprogrammer commented on Task03&Task04/main/Tree.kt
> +        return TreeIterator()
тут видимо более идиоматично возвращать ``` object : Iteraror .. { override ...} ```

2019-05-16 23:14 UTC, Tiltedprogrammer commented on Task03&Task04/main/Tree.kt
> +    private inner class TreeIterator() : Iterator<NodeType> {
Итератор возвращает узел, что дает возможность менять узел и соответственно дерево, это как-то неочень.

2019-05-16 23:14 UTC, Tiltedprogrammer commented on Task03&Task04/main/Tree.kt
> +                nextNode = getMinNode(node?.right) ?: throw NullPointerException("There are no more nodes in the tree")
Кажется тут это исключение никогда не бросится

2019-05-16 23:14 UTC, Tiltedprogrammer commented on Task03&Task04/test/BSTIterationTest.kt
> +        try {
в Junit есть средства, дабы не писать в коде теста try catch, собственно советуют ими пользоваться. https://github.com/junit-team/junit4/wiki/exception-testing

2019-05-21 06:16 UTC, nikitavlaev commented
Все проблемы, описанные выше, кроме идиоматичного возвращения итератора, решены. 
@Tiltedprogrammer @EgorkaKulikov жду фидбека

2019-05-21 06:19 UTC, nikitavlaev commented on Task03&Task04/main/Tree.kt
> +        return TreeIterator()
К сожалению, не нашел ни одного упоминания такого способа возвращения итератора, зато нашел, что его возвращают так, как сделано. Прошу сорс, где описан такой способ.

2019-05-21 11:32 UTC, Tiltedprogrammer approved these changes
Апрув, единственное что мне интересно зачем вам equals на деревьях? Если для тестов, то т.к. у вас internal root то можно и руты сравнивать.

2019-05-21 11:32 UTC, Tiltedprogrammer commented on Task03&Task04/main/Tree.kt
> +        return TreeIterator()
Про идиоматичность я, конечно, загнул, но так у вас и класс и метод, которы единственное, что делает это возвращает объект. Вот [тут](http://www.cs.cornell.edu/courses/cs211/2005fa/Lectures/L15-Iterators%20&%20Inner%20Classes/L15cs211fa05.pdf), например, написано, что это хорошо. Но я не имел в виду, что ваш способ плохой, просто держу в курсе

2019-05-21 18:53 UTC, EgorkaKulikov requested changes
Не нашёл отчёта о прогоне тестов, а также написал пару вопросов по коду. А также нужно зарезолвить конфликты.

2019-05-21 18:53 UTC, EgorkaKulikov commented on Task03&Task04/main/AVLTree.kt
> +        return javaClass.hashCode()
Ой! А вот я не уверен, что так сработает. Точно ли сохранятся необходимые инварианты на equals и hashCode? Мне кажется, эта функция должна зависеть от полей, рассматриваемых в equals. Или хочу пруфлинк, почему так сработает.

2019-05-21 18:53 UTC, EgorkaKulikov commented on Task03&Task04/main/Node.kt
> +        internal set
А в чём смысл именно internal set? Почти никогда не встречал такого в промышленном коде..

2019-05-21 18:53 UTC, EgorkaKulikov commented on Task03&Task04/main/Tree.kt
> +    private inner class TreeIterator() : Iterator<NodeType> {
Да, и это существенная проблема, какие идеи по поводу её фикса?

2019-05-21 19:52 UTC, nikitavlaev commented on Task03&Task04/main/Node.kt
> +        internal set
@EgorkaKulikov смысл именно в том, что когда мы возвращаем ноду с итератора, мы не можем в ней ничего изменить кроме value(изменение которого не влияет на структуру дерева, поэтому с моей точки зрения это можно воспринимать как дополнительную функциональность). И ничего плохого в том, что с итератора можно смотреть (и только!) содержимое ноды, например это позволяет узнать структуру дерева(если очень интересно).

2019-05-21 20:05 UTC, nikitavlaev commented on Task03&Task04/main/AVLTree.kt
> +        return javaClass.hashCode()
@EgorkaKulikov Вообще, на самом деле не очень ясно, зачем hashCode(), я сделал для галочки, нигде в задаче он не используется, поэтому наверное его просто нужно убрать?

2019-05-22 14:23 UTC, closed without merging