Task03_Akhmetyanov
EgorkaKulikov/spbu-se2019-spring pull request #68
Opened 2019-05-09 19:41 UTC by azat-akhm

2019-05-09 19:48 UTC, azat-akhm commented
Принтер позаимствовал у лидера команды, могу свой написать, если понадобится

2019-05-11 21:04 UTC, EgorkaKulikov commented
Я не против заимствования принтера

2019-05-21 20:49 UTC, EgorkaKulikov requested changes
Очень достойный код, на мой взгляд. Мелкие замечания.
И не хватает отчёта о прогоне общекомандных тестов.

2019-05-21 20:49 UTC, EgorkaKulikov commented on Task03/AVLTree.kt
> +        public fun newHeight() {
Не вполне понятно, что делает эта функция, слово this в 20 строчке лишнее

2019-05-21 20:49 UTC, EgorkaKulikov commented on Task03/AVLTree.kt
> +    private fun AVLNode.rotateLeftHeightFix() {
Я тут не шарю, что нам даёт явное указание  AVLNode в имени метода?

2019-05-21 20:49 UTC, EgorkaKulikov commented on Task03/AVLTree.kt
> +        root?.let { (root as AVLNode).print(0, 0) }
А как поведёт себя такая штука, если root as AVLNode окажется null? Согласны ли мы на это?

2019-05-21 20:49 UTC, EgorkaKulikov commented on Task03/AVLTree.kt
> +        root?.let { (root as AVLNode).print(0, 0) }
Вообще, конечно, большое количество кастований - признак чего-то нехорошего в архитектуре.
Возможное решение - вынос той части метода, которая относится к общему руту, в отдельное место, а в отдельных реализациях уже держать специфичную часть. Но в данном случае ваш вариант вполне нормален.

2019-05-21 20:49 UTC, EgorkaKulikov commented on Task03/BalancedSearchTree.kt
> +        internal fun uncle(): Node? {
А почему это метод, а не свойство?

2019-05-21 20:49 UTC, EgorkaKulikov commented on Task03/Color.kt
> +    RED, BLACK
Лучше в столбик и с плавающей запятой после последнего элемента. Тогда меньше конфликтов потом при мёрдже будет, если два человека в двух ветках добавят по новому элементу (не в это конкретно перечисление, а в какое-то другое).

2019-05-21 20:49 UTC, EgorkaKulikov commented on Task03/AVLTree.kt
> +            val leftCorrectnessAndHeight = (this.left as AVLNode?)?.verifyAVL()
Лучше все такие касты отдельным действием с дальнейшей проверкой, привелось ли. Меньше неожиданных эксепшенов потом будет.

2019-05-22 11:27 UTC, azat-akhm commented on Task03/AVLTree.kt
> +    private fun AVLNode.rotateLeftHeightFix() {
Зачем-то сделал их функциями расширения, теперь просто убрал их в AVLNode и явное указание не нужно

2019-05-22 11:29 UTC, azat-akhm commented on Task03/AVLTree.kt
> +        root?.let { (root as AVLNode).print(0, 0) }
Поменял на действие с проверкой is AVLNode

2019-05-22 11:30 UTC, azat-akhm commented on Task03/BalancedSearchTree.kt
> +        internal fun uncle(): Node? {
В данном случае и правда лучше свойство с геттером, поменял

2019-05-22 11:30 UTC, azat-akhm commented on Task03/BalancedSearchTree.kt
> +        internal fun uncle(): Node? {
И для остальных подобных функций тоже

2019-05-22 20:58 UTC, merged