Task03_Gordienko
EgorkaKulikov/spbu-se2019-spring pull request #69
Opened 2019-05-09 19:58 UTC by GordienkoEgor

2019-05-17 22:56 UTC, Tiltedprogrammer requested changes
Настораживают касты ```as```, но это претензии к архитектуре. А из замечаний: поправьте assert'ы в тестах и ответьте на вопрос про enum и будет апрув, по коду все ок.

2019-05-17 22:56 UTC, Tiltedprogrammer commented on Task03/tests/BinarySearchTreeTests.kt
> +import org.junit.jupiter.api.Assertions.assertEquals
для единообразности следовало бы во всех тестах такой импорт сделать

2019-05-17 22:56 UTC, Tiltedprogrammer commented on Task03/tests/AVLTests.kt
> +        assertEquals(tree.find(6), null)
expected actual параметры в ассерте не на тех местах

2019-05-17 22:56 UTC, Tiltedprogrammer commented on Task03/trees/BinarySearchTree.kt
> +            return ((this.left == null) || (this.left!!.key <= this.key
Немного странное название функции, т.к. она проверяет порядок ключей а не совсем поиск

2019-05-17 22:56 UTC, Tiltedprogrammer commented on Task03/trees/RBTree.kt
> +enum class Color {
а почему enum не internal?

2019-05-18 18:01 UTC, GordienkoEgor commented
Исправил замечания

2019-05-18 20:20 UTC, Tiltedprogrammer approved these changes

2019-05-18 21:32 UTC, EgorkaKulikov commented on Task03/tests/AVLTests.kt
> +            tree.insert(Random.Default.nextInt(), Random.Default.nextInt())
А петель так не получится случайно?

2019-05-18 21:33 UTC, EgorkaKulikov commented on Task03/tests/AVLTests.kt
> +    fun basicTest() {
А чем отличается basicTest от correctnessTest? Стороннему человеку непонятно. Имена плохие.

2019-05-19 00:07 UTC, GordienkoEgor commented on Task03/tests/AVLTests.kt
> +            tree.insert(Random.Default.nextInt(), Random.Default.nextInt())
Не должно, т.к. если key совпадет с уже существующим, то просто заменится value

2019-05-21 19:52 UTC, EgorkaKulikov commented on Task03/tests/AVLTests.kt
> +            tree.insert(Random.Default.nextInt(), Random.Default.nextInt())
Стрёмная достаточно логика, но допустим

2019-05-21 19:52 UTC, EgorkaKulikov commented
Жду исправления небольших замечаний и будет глобальный аппрув

2019-05-21 20:00 UTC, GordienkoEgor commented on Task03/tests/AVLTests.kt
> +    fun basicTest() {
Названия этих тестов изменил

2019-05-22 21:02 UTC, merged