Task03 and Task04 completed
EgorkaKulikov/spbu-se2019-spring pull request #72
Opened 2019-05-09 23:32 UTC by GamaonovAlan

Binary search tree, AVL tree and Red-Black tree + iterator + tests + results of passing team tests

2019-05-24 15:49 UTC, NikitaMishin commented on Task03 + Task04/AVLTree/AVLTree.kt
> +    {
можно сразу писать   = when {}

2019-05-24 15:51 UTC, NikitaMishin commented on Task03 + Task04/AVLTree/Node.kt
> +package AVLTree
package с маленькой буквы

2019-05-24 15:52 UTC, NikitaMishin commented on Task03 + Task04/AVLTree/Node.kt
> +class Node<K : Comparable<K>, V> (var key   : K,
на каком основании key изменяемый?

2019-05-24 15:54 UTC, NikitaMishin commented on Task03 + Task04/AVLTree/Node.kt
> +    fun rotateLeft()
а зачем нам торчащие функции такие? private/ internal?

2019-05-24 16:06 UTC, NikitaMishin requested changes
тесты ок, но можно было бы сгенерировать хэтэмээлку и раз норм архитектура, единообразные тесты вынести в отдельный класс
4) итератор норм, наконец-то нет копипастыыыы
3) надо бы с модификаторами исправить и пара мелких предложений (см комментарии)
+ public рут - не гуд(
А так более менее впечатление по 3-4 задачам. Только в дедлайны опасно сдавать)

2019-05-24 16:06 UTC, NikitaMishin commented on Task03 + Task04/AbstractTree.kt
> +    var root : N? = null
как-то нехорошо"
у нас пользователь может получить доступ к руту и все поломать. Надо как-то исправить

2019-05-24 16:06 UTC, NikitaMishin commented on Task03 + Task04/binarySearchTree/BSTree.kt
> +package binarySearchTree
к слову о именовании. БЫла бы она у вас единообразная, но тут , например, с маленькой буквы.
На военке есть фраза, безобразно, но единообразно)))))

2019-05-24 16:06 UTC, NikitaMishin commented on Task03 + Task04/binarySearchTree/BSTree.kt
> +        return when
аналлогично можно вынести наверх when

2019-05-24 16:06 UTC, NikitaMishin commented on Task03 + Task04/redBlackTree/Node.kt
> +                                  private var isBlack : Boolean = false
enumы хотят очень появиться))

2019-05-24 16:06 UTC, NikitaMishin commented on Task03 + Task04/redBlackTree/Node.kt
> +    fun rotateRight()
аналогично с модификаторами доступа

2019-05-24 16:06 UTC, NikitaMishin commented on Task03 + Task04/redBlackTree/RBTree.kt
> +        return when
lift when

2019-05-24 16:06 UTC, NikitaMishin commented on Task03 + Task04/tests/redBlackTree/RB_TreeTest.kt
> +    fun searching_existing_key_succes_asserted() {
вот вам, кстати, благодаря нормальной архитектуре, возможно избежать тупой копипасты даже в тестах! Общие тесты можно в один класс запихать

2019-05-24 16:08 UTC, NikitaMishin commented on Task03 + Task04/redBlackTree/Node.kt
> +                                  private var isBlack : Boolean = false
ну и опять насчет видимости

2019-05-24 18:39 UTC, NikitaMishin requested changes

2019-05-24 18:39 UTC, NikitaMishin commented on Task03 + Task04/AbstractTree.kt
> +    override fun iterator(): Iterator<N>
если мы возвращем node, надо позаботиться о том, чтобы пользователь не имел доступа к внутренним данным - parent,left,right

2019-05-26 11:11 UTC, EgorkaKulikov requested changes

2019-05-26 11:11 UTC, EgorkaKulikov commented on Task01/Main.kt
> +    {
Алгоритм Форда-Беллмана должен работать в худшем случае за O(VE). Здесь же я наблюдаю три вложенных цикла по всем вершинам, что явно имеет другую асимптотику работы.

2019-05-26 11:11 UTC, EgorkaKulikov commented on Task01/Main.kt
> +    private fun getForBellmanPath(k : Int) : Array<Int>
Ford

2019-05-26 11:11 UTC, EgorkaKulikov commented on Task01/Main.kt
> +    fun printShortestPaths(k : Int)
k - номер вершины, от которой ищется кратчайший путь? Не вполне ясно

2019-05-26 11:11 UTC, EgorkaKulikov commented on Task01/Main.kt
> +            if (max < row.max() as Int)
row.max() незачем брать два раза, а потом ещё и два раза кастовать

2019-05-26 11:11 UTC, EgorkaKulikov commented on Task01/Main.kt
> +    private fun findMin() : Int
Выглядит весьма странно, когда функции findMax и findMin имеют принципиально разное содержание

2019-05-26 11:11 UTC, EgorkaKulikov commented on Task02/Code review.txt
> +данным языком только в этом семестре, а потому не знаю чем отличаются его версии.
А если работодатель попросит вас подправить и осовременить код, написанный на C++ 98, вы откажетесь, потому что тогда не только не ознакомились с языком, но даже не родились?

2019-05-26 11:11 UTC, EgorkaKulikov commented on Task03 + Task04/tests/AVLTree/AVL_NodeTest.kt
> +    @DisplayName("Pair right rotate Case 2")
А что такое case2, case3?

2019-05-26 11:11 UTC, EgorkaKulikov commented on Task03 + Task04/tests/AVLTree/AVL_NodeTest.kt
> +
Не нашёл тестов на исключительные ситуации, в которых было бы что-то вроде assertFailsWith

2019-05-26 11:11 UTC, EgorkaKulikov commented on Task06/src/Main.kt
> +    val data = File(PATH_TO_PICTURE).readBytes()
При таком подходе никто, кроме вас, воспользоваться программой не сможет, если только не разберётся по исходникам, куда же нужно положить картинку.

2019-05-26 11:11 UTC, EgorkaKulikov commented on Task06/src/Main.kt
> +        {
Магия с константами FF или FF00 нуждается в комментариях, иначе код совершенно не сопровождаем.

2019-05-27 17:46 UTC, GamaonovAlan commented on Task03 + Task04/AbstractTree.kt
> +    override fun iterator(): Iterator<N>
> если мы возвращем node, надо позаботиться о том, чтобы пользователь не имел доступа к внутренним данным - parent,left,right

Проблема в том, что нельзя ослабить модификатор доступа. Я хотел полям leftChild, rightChild и parent задать internal set, чтобы извне нельзя было менять эти значения, но так как в интерфейсе INode эти поля public, не получается так сделать

2019-10-04 18:59 UTC, merged