Task04_Lunev
EgorkaKulikov/spbu-se2019-spring pull request #77
Opened 2019-05-11 20:36 UTC by artemlunev2000

2019-05-11 21:48 UTC, EgorkaKulikov requested changes
Хорошо, мелкие замечания

2019-05-11 21:48 UTC, EgorkaKulikov commented on Task04/Task4.kt
> +class IterableSearchTree<K: Comparable<K>, T>: Iterable<T> {
А почему это класс, а не интерфейс?

2019-05-11 21:48 UTC, EgorkaKulikov commented on Task04/Task4.kt
> +    fun inserte (key: K, value: T) {
insert

2019-05-11 21:48 UTC, EgorkaKulikov commented on Task04/Task4.kt
> +                    else {
Если там return, то else вроде как и не нужен

2019-05-11 21:48 UTC, EgorkaKulikov commented on Task04/Task4.kt
> +            val ListOfNodes = LinkedList<Node>()
В строках 61-62 странное изменение форматирования

2019-05-16 17:46 UTC, EgorkaKulikov commented
Пока исправлений так и не вижу...

2019-05-20 16:07 UTC, artemlunev2000 commented on Task04/Task4.kt
> +                    else {
Нужен, return находится в if, который сигнализирует о том, что мы наткнулись на ячейку null и туда вставляем. Если нет, то продолжаем поиск

2019-05-20 16:10 UTC, artemlunev2000 commented on Task04/Task4.kt
> +class IterableSearchTree<K: Comparable<K>, T>: Iterable<T> {
Не вижу плюсов от использования здесь интерфейса

2019-05-21 17:41 UTC, EgorkaKulikov commented on Task04/Task4.kt
> +class IterableSearchTree<K: Comparable<K>, T>: Iterable<T> {
Ну потому что IterableSearchTree - это, по-хорошему, некая абстрактая штука, которая отличается от обычного SearchTree только итерируемостью и больше ничего особенного своего не имеет. Вы же здесь залепили всё это в одно место.

2019-05-21 17:41 UTC, merged

2019-05-21 17:42 UTC, EgorkaKulikov commented
Про IterableSeachTree лучше исправить в рамках основной задачи по деревьям.