Task01_Kuzivanov
EgorkaKulikov/spbu-se2019-spring pull request #8
Opened 2019-03-13 12:14 UTC by SergeyKuz1001

2019-03-16 21:36 UTC, EgorkaKulikov requested changes

2019-03-16 21:36 UTC, EgorkaKulikov commented on Task1/main.kt
> +class SymMatrix(val N : Int) {
Если Вы создаёте столь большой класс, его явно следует вынести в отдельный файл.

2019-03-16 21:36 UTC, EgorkaKulikov commented on Task1/main.kt
> +    operator fun get(i: Int, j: Int) : Int? {
А вот уместно ли это и больше в стиле "как круто, что я научился переопределять операторы"? 
Ведь по сути мы выбирает один элементы из таблицы, тогда как смысл геттера для таблицы - всё же скорее взяти информации о таблице, пусть и с какими-то "спецэффектами".
Я не настаиваю на том, что нужно переделывать, скорее предлагаю задуматься.

2019-03-16 21:36 UTC, EgorkaKulikov commented on Task1/main.kt
> +class ArrayFrom1(val N : Int, private val funGenerator : (Int) -> Int?) {
Очень неудачное название класса, как и вся строка 42

2019-03-16 21:36 UTC, EgorkaKulikov commented on Task1/main.kt
> +    override fun hashCode(): Int {
А это автогенерация идеи или откуда?

2019-03-16 21:36 UTC, EgorkaKulikov commented on Task1/main.kt
> +class Heap {
Вспомните мои слова с пары про "простынный" код

2019-03-16 21:36 UTC, EgorkaKulikov commented on Task1/main.kt
> +    println("Граф состоит из ${graph.N} ${if (graph.N == 1) "вершины" else "вершин"} " +
Не надо условных операторов внутри интерполированных строк.

2019-03-16 21:36 UTC, EgorkaKulikov commented on Task1/main.kt
> +                if (length[to] == null) {
Здесь очень много оператора !!

@KutuevVladimir, а что вообще говорит наука по этому поводу?
Немного пугают такие строки из соображения "всё, что может породить исключение, обязательно его породит" С другой стороны, банальная выборка из массива тоже потенциально опасно, но их делают...
И вот когда readline()!! при чтении входных данных задачи не срабатывает, то тут понятно, что нужно ронять приложения. А из-за lenght[v] падать не хочется.

2019-03-16 21:36 UTC, EgorkaKulikov commented on Task1/main.kt
> +                result += " ".repeat(maxIntLength - this[i, j].length()) + "${this[i, j] ?: NULL_BRANCH} "
" ".repeat(...) выглядит очень странно

2019-03-16 21:36 UTC, EgorkaKulikov commented on Task1/main.kt
> +        this.toString().length
В коде зашкаливающе часто присутствует слово this. Оно точно везде нужно? Я не про это конкретно место, а в целом.

2019-03-17 09:08 UTC, KutuevVladimir commented on Task1/main.kt
> +                if (length[to] == null) {
Вообще таких штук - `Int?`надо бы избегать, если нет крайнейнеобходимости. Например для массива `length` показателем того, что до вершины путь не подсчитан, может являться -1 (если нет отрицательных рёбер), тогда -1 в массиве p будет говорить о недостижимости вершины. Можно завести массив `used: Boolean`. И эти варианты помогут совсем убрать `!!` из метода. Вообще использовать `!!` надо только в случае крайней необходимости (Выше я показал, что таковой нет). Вообще если можно обойтись не nullable переменной, советую так делать.

2019-03-17 09:33 UTC, KutuevVladimir commented on Task1/main.kt
> +                if (length[to] == null) {
Так `readline()!!` я бы тоже не советовал делать, т.к полетевшее исключение несёт мало информации. Лучше что-нибудь типа`readline() ?: throw IOException("Cannot read data")`. А от NPE хочется избавиться совсем (иначе зачем нам Kotlin).

2019-03-17 15:58 UTC, SergeyKuz1001 commented
Недочёты исправлены

2019-03-17 18:54 UTC, KutuevVladimir commented on Task1/main.kt
> +    val heap = sortedSetOf<SortedVertex>()
Вы, похоже, путаете heap и priority queue. Priority queue - абстрактная структура данных, в которую можно добавить элемент и извлечь элемент с минимальным/максимальным приоритетом. Heap - конкретная структура данных, реализующая priority queue. 
Поэтому именовать переменную так не стоит (читать код людям, это сбивает).
Вы используете TreeSet(SortedSet), в стандартной библиотеке java есть класс PriorityQueue, чем вызван выбор в пользу SortedSet?

2019-03-17 19:00 UTC, KutuevVladimir commented on Task1/SortedVertex.kt
> +class SortedVertex(val vertex: Int, val length: Int): Comparable<SortedVertex> {
Необходимо ли создавать такой класс? Используемый компаратор аналогичен стандартному компаратору пары `(length, vertex): Pair<Int, Int>`.
Именование класса не даёт правильного понимания того, что это за сущность (даже приблизительно). Поддерживать код с плохим именованием сложно)

2019-03-18 19:11 UTC, SergeyKuz1001 commented
Недочёты исправлены

2019-03-18 20:01 UTC, EgorkaKulikov commented on Task1/main.kt
> +            else if (length[to]!! > length[v]!! + graph[v, to]!!) {
А вот кстати интересно, мне тут Влада ссылку в своём пулреквесте скидывала, что в котлин стайле рекомендуют else на той же строчке начинать, что и закрывающая скобочка

2019-03-18 20:04 UTC, EgorkaKulikov commented on Task1/main.kt
> +    val heap = sortedSetOf<SortedVertex>()
Спасибо большое, Вова

2019-03-18 20:04 UTC, EgorkaKulikov approved these changes

2019-03-26 19:27 UTC, merged