Task03_Duletov
EgorkaKulikov/spbu-se2019-spring pull request #88
Opened 2019-05-14 20:51 UTC by Duletov

2019-05-22 22:24 UTC, EgorkaKulikov requested changes
Бросается в глаза проблема с кастами, надо с ней что-то делать. И есть явные вопросы по тестам. Остальное вроде нормально.

2019-05-22 22:24 UTC, EgorkaKulikov commented on Task03/Tests/AVLTreeTest.kt
> +    private fun randomAVLTree(size: Int): AVLTree<Int, Int> {
Моё представление о юнит-тестах говорит, что такой тест должен показывать, что на конкретном наборе входных данных, иллюстрирующих конкретный случай поведения системы, всё работает корректно или же наоборот, вот такой случай разломался.
Если же упадёт на рандомном дереве, мы не получим никакой информации о том, что именно упало. Равно как и его прохождение не будет ничего гарантировать. Такой тест хорош при первичной отладке, но для сопровождения системы бесполезен.

2019-05-22 22:24 UTC, EgorkaKulikov commented on Task03/Tests/AVLTreeTest.kt
> +        val tree = randomAVLTree(1000)
1000 - это не стресс

2019-05-22 22:24 UTC, EgorkaKulikov commented on Task03/Tests/BinarySearchTreeTest.kt
> +    fun equalityNodesTest(){
Наверное, недочитатали у других, но что в содержательном смысле проверяет этот тест?

2019-05-22 22:24 UTC, EgorkaKulikov commented on Task03/src/AVLTree.kt
> +                right = (this.right as AVLNode).height
Конечно, обилие таких кастов не красит код. А нельзя ли эти кастования вынести на уровень переопределяемых свойств BalancingNode внутри AVLNode?
И что делали другие люди в команде? Всё-таки такого дикого числа кастов я у других, кажется, не видел

2019-05-22 22:24 UTC, EgorkaKulikov commented on Task03/src/AVLTree.kt
> +                right = (this.right as AVLNode).height
Ну и такой код небезопасен, если кастование завершиться с null, а полагаться, что такого никогда не будет, довольно опасно.

2019-05-22 22:24 UTC, EgorkaKulikov commented on Task03/src/AVLTree.kt
> +                right = (this.right as AVLNode).height
@KutuevVladimir @NikitaMishin @TiltedProgrammer если смотрели кого-то из этой команды, а Дима не вытянется за соломинку сам, попробуйте спасти человека, пожалуйста

2019-05-22 22:24 UTC, EgorkaKulikov commented on Task03/src/BalancedSearchTree.kt
> +        fun grandparent(): Node? {
Почему это метод, а не свойство?

2019-05-22 22:24 UTC, EgorkaKulikov commented on Task03/src/BalancedSearchTree.kt
> +    internal fun parentsCorrectness(): Boolean {
Лучше verifyParentCorrectness, ну и вообще глаголы в названиях методов - наше всё

2019-05-22 22:24 UTC, EgorkaKulikov commented on Task03/src/BinarySearchTree.kt
> +        innerInsert(key, value)
Реализация функции выглядит очень странно: одно действие - вызов другой функции с теми же параметрами

2019-05-22 22:24 UTC, EgorkaKulikov commented on Task03/src/BinarySearchTree.kt
> +        return (((curNode.left == null) || (curNode.key >= curNode.left!!.key && verifySearch(curNode.left!!))) &&
Либо много лишних скобок, либо надо разбивать условие

2019-05-22 22:24 UTC, EgorkaKulikov commented on Task03/src/Color.kt
> +    RED, BLACK
Лучше в столбик и с плавающей запятой. При параллельном изменении в двух ветках так будут конфликты

2019-05-23 15:58 UTC, Duletov commented on Task03/Tests/AVLTreeTest.kt
> +    private fun randomAVLTree(size: Int): AVLTree<Int, Int> {
Согласен, случайный набор не очень хорошо отражает работоспособность программы, но отладиться до рабочего состояния позволяет. Тесты, вообще, у нас общие на команду, но если надо, могу написать ещё.

2019-05-23 15:59 UTC, Duletov commented on Task03/Tests/AVLTreeTest.kt
> +        val tree = randomAVLTree(1000)
Исправил на 10000. Большие цифры сильно замедляют тестирование.

2019-05-23 16:00 UTC, Duletov commented on Task03/Tests/BinarySearchTreeTest.kt
> +    fun equalityNodesTest(){
Не нашёл обсуждения этой ошибки, в пулреквестах нашей команды. Исправил ошибку с повторением строки.

2019-05-23 16:01 UTC, Duletov commented on Task03/src/AVLTree.kt
> +                right = (this.right as AVLNode).height
Да, обилие кастов это проблема нашей команды. По возможности убрал лишние касты и проверил корректность при null. Теперь у меня чуть ли не меньше всех кастов и, боюсь, дальше их будет убирать проблематично.

2019-05-23 16:02 UTC, Duletov commented on Task03/src/BalancedSearchTree.kt
> +        fun grandparent(): Node? {
Это метод, чтобы он был однообразнее с uncle и короче в записи (в моём представлении).

2019-05-23 16:02 UTC, Duletov commented on Task03/src/BalancedSearchTree.kt
> +    internal fun parentsCorrectness(): Boolean {
Исправил

2019-05-23 16:03 UTC, Duletov commented on Task03/src/BinarySearchTree.kt
> +        innerInsert(key, value)
К сожалению, издержки архитектуры. При изменении перестают работать тесты.

2019-05-23 16:03 UTC, Duletov commented on Task03/src/BinarySearchTree.kt
> +        return (((curNode.left == null) || (curNode.key >= curNode.left!!.key && verifySearch(curNode.left!!))) &&
Убрал лишние

2019-05-23 16:03 UTC, Duletov commented on Task03/src/Color.kt
> +    RED, BLACK
Исправил. Также изменил видимость класса

2019-05-23 21:25 UTC, EgorkaKulikov commented on Task03/Tests/AVLTreeTest.kt
> +    private fun randomAVLTree(size: Int): AVLTree<Int, Int> {
Видимо, мы немного недосмотрели у других. Наша ошибка. Доделывать не надо, просто примите в сведению.

2019-05-23 21:28 UTC, EgorkaKulikov commented on Task03/src/BalancedSearchTree.kt
> +        fun grandparent(): Node? {
А я бы и uncle сделал свойством.
Свойство это как раз поле, которое ведёт себя как метод.
Оставим советом на будущее

2019-05-23 21:31 UTC, EgorkaKulikov commented on Task03/src/AVLTree.kt
> +                right = (this.right as AVLNode).height
Стало приличнее, но всё равно, конечно, так себе...

2019-05-23 21:32 UTC, merged