Task01_Konnov
EgorkaKulikov/spbu-se2019-spring pull request #9
Opened 2019-03-13 12:22 UTC by KirillKonnov

2019-03-16 21:45 UTC, EgorkaKulikov requested changes
Убедительная просьба не повторять в своём коде те косяки, которые обсуждались несколько дней назад на паре...

2019-03-16 21:45 UTC, EgorkaKulikov commented on Task01/Task01.kt
> +const val INF = 1000001
Это не информативно. Либо имя другое, либо комментарий.

2019-03-16 21:45 UTC, EgorkaKulikov commented on Task01/Task01.kt
> +val scan = java.util.Scanner(System.`in`)
На Kotlin native будет работать?

2019-03-16 21:45 UTC, EgorkaKulikov commented on Task01/Task01.kt
> +    var i = 0
i=0 злостное зло

2019-03-16 21:45 UTC, EgorkaKulikov commented on Task01/Task01.kt
> +        val value = (1..99).random()
Вспомните разговор с пары про магические константы. 99, 101 у вас ещё в другом месте. Пора уже избавляться.

2019-03-16 21:45 UTC, EgorkaKulikov commented on Task01/Task01.kt
> +    for(i in 0..(matrix.size - 1)){
until

2019-03-16 21:45 UTC, EgorkaKulikov commented on Task01/Task01.kt
> +    while(i != matrix.size - 1){
Как по поводу content equals?

2019-03-16 21:45 UTC, EgorkaKulikov commented on Task01/Task01.kt
> +val scan = java.util.Scanner(System.`in`)
И почему оно определяется вне функции main - единственного места, где используется

2019-03-16 21:45 UTC, EgorkaKulikov commented on Task01/Task01.kt
> +        println(0)
И что такая запись в логах нам даёт?

2019-03-17 20:49 UTC, NikitaMishin commented on Task01/Task01.kt
> +    while(i != matrix.size - 1){
а не вынести ли  отедельно как unit тест? или тут просто чисто показать, что оба одинаково работают для положительных весов?

2019-03-18 19:58 UTC, EgorkaKulikov commented on Task01/Task01.kt
> +    while(i != matrix.size - 1){
скорее даже проверить себя, что написано без багов
это в любом случае не юнит-тест в классическом его понимании, да и мы их ещё не проходили

2019-03-18 19:59 UTC, EgorkaKulikov commented
Жду сообщения об исправлении

2019-03-19 11:50 UTC, KirillKonnov commented on Task01/Task01.kt
> +const val INF = 1000001
Имя изменено на INFINITIY, надеюсь, это информативно

2019-03-19 11:50 UTC, KirillKonnov commented on Task01/Task01.kt
> +val scan = java.util.Scanner(System.`in`)
Определил в функции main

2019-03-19 11:52 UTC, KirillKonnov commented on Task01/Task01.kt
> +    var i = 0
имя i изменено на более информативное

2019-03-19 11:53 UTC, KirillKonnov commented on Task01/Task01.kt
> +    for(i in 0..(matrix.size - 1)){
.. изменил на until

2019-03-19 11:53 UTC, KirillKonnov commented on Task01/Task01.kt
> +    while(i != matrix.size - 1){
Изменил на content equals

2019-03-19 11:54 UTC, KirillKonnov commented on Task01/Task01.kt
> +        println(0)
Тут должно было быть Min weight = 0

2019-03-19 11:54 UTC, KirillKonnov commented on Task01/Task01.kt
> +        println(0)
Исправлено

2019-03-19 11:55 UTC, KirillKonnov commented on Task01/Task01.kt
> +        val value = (1..99).random()
добавлена константа MAX_WEIGHT равная 100

2019-03-19 20:38 UTC, EgorkaKulikov commented on Task01/Task01.kt
> +const val INF = 1000001
А как вы сами считаете? Мне кажется, нет. Какой смысл у этого объекта? Длина бесконечно длинного пути, которую никакой путь не привысит? Тогда так и назовите: InfinitePathLength.

2019-03-19 20:40 UTC, EgorkaKulikov commented on Task01/Task01.kt
> +const val INF = 1000001
Аппрувлю, в дальнейшем следите за этим, всё же код не только пишут, но и читают.

2019-03-19 20:40 UTC, EgorkaKulikov approved these changes

2019-03-26 19:27 UTC, merged