Task03_Tsirikov
EgorkaKulikov/spbu-se2019-spring pull request #94
Opened 2019-05-19 14:28 UTC by Tsirikov

2019-05-24 16:18 UTC, Tiltedprogrammer requested changes
Мне не очень понравился код стайл с переносом скобок, все же рекомендуют делать как [тут](https://kotlinlang.org/docs/reference/coding-conventions.html#formatting), и множество кастов настораживает, но это, видимо, "особенности архитектуры"

2019-05-24 16:18 UTC, Tiltedprogrammer commented on Task03/main/BST.kt
> +  var root: Node? = null
почему root не internal?

2019-05-24 16:18 UTC, Tiltedprogrammer commented on Task03/main/RB.kt
> +    internal fun getUncle(): RBNode?
Более идеологично сделать эту функцию полем с геттером.

2019-05-24 16:18 UTC, Tiltedprogrammer commented on Task03/tests/BSTTests.kt
> +  fun stressStructure()
Какую смысловую нагрузку несут эти тесты? На сколько быстро по дереву можно проверить инварианты?
На практике же не инварианты проверяют, а вставляют/ищут.

2019-05-24 16:18 UTC, Tiltedprogrammer commented on Task03/main/AVL.kt
> +      var leftHeight = 0
более коротко и по-котлиновски как-то так: ``` var leftHeigh = (left as? AVLNode)?.height ?: 0``` , хотя я вот написал и теперь не уверен, что это лучше.

2019-05-24 17:34 UTC, Tsirikov commented
Изменения в коде согласно замечаниям.
Проверка ненарушения структуры сделана через случайные числа, так что тест с большими значениями всего лишь более надёжный вариант базового, который может пройти при удачно подобранных значениях, в то время как алгоритм будет работать неверно, например.

2019-05-24 17:57 UTC, Tiltedprogrammer approved these changes

2019-05-25 04:26 UTC, EgorkaKulikov reviewed
Минимальные дополнительные замечания. Поправьте моё и Лёшино и будет аппрув по деревьям и тестам

2019-05-25 04:26 UTC, EgorkaKulikov commented on Task03/main/AVL.kt
> +                val temporary = (left as AVLNode).verifyAVL()
Вызов метода для каста всегода опасен тем, что каст не сработает. Даже если в сегодняшней реализации он срабатывает всегда

2019-05-25 04:26 UTC, EgorkaKulikov commented on Task03/main/AVL.kt
> +            || ((root as AVLNode).verifyAVL().first)
Форматирование, условия друг под другом

2019-05-25 04:26 UTC, EgorkaKulikov commented on Task03/main/RB.kt
> +    RED, BLACK
В столбик и с плавающей запятой. Несколько раз писал товарищам, почему.

2019-05-25 04:26 UTC, EgorkaKulikov commented on Task03/main/RB.kt
> +            get() {
Это хорошо, а то у многих метод, а не свойство

2019-05-25 04:26 UTC, EgorkaKulikov commented on Task03/tests/AVLTests.kt
> +    private fun randomAVLTree(size: Int): AVLTree<Int, Int> {
Посмотрите развёрнутый комментарий у Димы Дулетова, почему тест, основанный на рандоме - плохо

2019-05-25 06:05 UTC, Tsirikov commented
Исправлены касты и форматирование.
Комментарий про случайное тестирование прочёл, как-то не совсем согласен: прохождение действительно ничего не гарантирует, но если ошибка будет выловлена на случайном дереве, то можно выдать журнал последних операций или даже всё дерево, да и сам факт, что оно всё-таки падает при каком-то хаотичном входном наборе, который можно и не предусмотреть при конкретных тестах, вполне полезен.

2019-05-25 12:30 UTC, merged